### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError ibgateway/GWClient

### ISSUE THREAD

**Issue by tahahasan88** [QuantConnect/Lean#4151] opened 2020-03-03 15:52 UTC
I installed IBGateway nuget package into Lean launcher project and after running the project in visual studio, i get the following error stack trace:-

 InteractiveBrokersBrokerage.OnIbAutomaterErrorDataReceived(): Exception in thread "main" java.lang.NoClassDefFoundError: ibgateway/GWClient
20200303 19:46:29.167 Trace:: InteractiveBrokersBrokerage.OnIbAutomaterErrorDataReceived():     at ibautomater.IBAutomater.startIBGateway(IBAutomater.java:69)
20200303 19:46:29.168 Trace:: InteractiveBrokersBrokerage.OnIbAutomaterErrorDataReceived():     at ibautomater.IBAutomater.main(IBAutomater.java:55)
20200303 19:46:29.171 Trace:: InteractiveBrokersBrokerage.OnIbAutomaterErrorDataReceived(): Caused by: java.lang.ClassNotFoundException: ibgateway.GWClient
20200303 19:46:29.172 Trace:: InteractiveBrokersBrokerage.OnIbAutomaterErrorDataReceived():     at java.net.URLClassLoader.findClass(Unknown Source)
20200303 19:46:29.172 Trace:: InteractiveBrokersBrokerage.OnIbAutomaterErrorDataReceived():     at java.lang.ClassLoader.loadClass(Unknown Source)
20200303 19:46:29.173 Trace:: InteractiveBrokersBrokerage.OnIbAutomaterErrorDataReceived():     at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
20200303 19:46:29.174 Trace:: InteractiveBrokersBrokerage.OnIbAutomaterErrorDataReceived():     at java.lang.ClassLoader.loadClass(Unknown Source)
20200303 19:46:29.174 Trace:: InteractiveBrokersBrokerage.OnIbAutomaterErrorDataReceived():     ... 2 more

Using visual studio 2019 .net Core 3.0.

**Comment by StefanoRaggi** [comment] 2020-03-11 14:41
Hi @tahahasan88, this error is usually seen when the IBGateway software is not installed correctly.

Not sure which IBGateway NuGet package you are referring to, LEAN and [IBAutomater](https://github.com/QuantConnect/IBAutomater) require the standalone versions of IBGateway (currently only version 974 is supported, the same version used in the QC cloud) and this should be the only installation prerequisite, the IBAutomater NuGet package is already referenced by LEAN  and does not require manual installation.

If you can't find the Windows installer for v974 on IB's website, you can download it from here:
http://cdn.quantconnect.com/interactive/ibgateway-latest-standalone-windows-x64-v974.4g.exe

Please let us know if this solves the issue.

**Comment by hyao** [comment] 2020-03-24 18:48
I have a similar problem here: ibgateway 978, testing a python algo, on Ubuntu 1804.

`20200325 02:37:54.044 Trace:: InteractiveBrokersBrokerage.OnIbAutomaterOutputDataReceived(): StartIBGateway(): starting IBGateway^M
20200325 02:37:54.204 Trace:: InteractiveBrokersBrokerage.OnIbAutomaterOutputDataReceived(): Exception in thread "main" java.lang.NoClassDefFoundError: ibgateway/GWClient^M
20200325 02:37:54.204 Trace:: InteractiveBrokersBrokerage.OnIbAutomaterOutputDataReceived():    at ibautomater.IBAutomater.startIBGateway(IBAutomater.java:69)^M
20200325 02:37:54.204 Trace:: InteractiveBrokersBrokerage.OnIbAutomaterOutputDataReceived():    at ibautomater.IBAutomater.main(IBAutomater.java:55)^M
20200325 02:37:54.204 Trace:: InteractiveBrokersBrokerage.OnIbAutomaterOutputDataReceived(): Caused by: java.lang.ClassNotFoundException: ibgateway.GWClient^M
20200325 02:37:54.204 Trace:: InteractiveBrokersBrokerage.OnIbAutomaterOutputDataReceived():    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)^M
20200325 02:37:54.205 Trace:: InteractiveBrokersBrokerage.OnIbAutomaterOutputDataReceived():    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)^M
20200325 02:37:54.205 Trace:: InteractiveBrokersBrokerage.OnIbAutomaterOutputDataReceived():    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)^M
`

The thing is: when I wait a few seconds, it seems to start, and the algo seems to work fine:

`20200325 02:38:53.928 Trace:: InteractiveBrokersBrokerage.InteractiveBrokersBrokerage(): Host: 127.0.0.1, Port: 4002, Account: DU1963743, AgentDescription: Individual^M
20200325 02:38:53.936 Trace:: InteractiveBrokersBrokerage.ResetHandler(): thread started.^M
20200325 02:38:53.974 Trace:: LiveTradingDataFeed.GetDataQueueHandler(): will use QuantConnect.Brokerages.InteractiveBrokers.InteractiveBrokersBrokerage^M
20200325 02:38:53.975 Trace:: LiveTradingDataFeed.GetDataChannelProvider(): will use DataChannelProvider^M
20200325 02:38:53.977 Trace:: BaseDataExchange(CustomDataExchange) Starting...^M
20200325 02:38:53.977 Trace:: BaseDataExchange(DataQueueExchange) Starting...`

So the trick is to wait a few moments and see if it runs ok. Meanwhile, please fix the error where the ibgateway class could not be found. 


Thanks,

**Comment by StefanoRaggi** [comment] 2020-03-24 19:38
@hyao The only IBGateway version currently supported is **v974**:
https://github.com/QuantConnect/IBAutomater/issues/10#issuecomment-602589282

**Comment by jaredbroad** [comment] 2020-03-26 23:28
Closing as using the wrong IBGateway version

**Closed by jaredbroad** 2020-03-26 23:28 UTC
