### ISSUE TITLE
Bug: IndicatorExtensions.Of not working in Python Research Notebooks

### ISSUE THREAD

**Issue by shilewenuw** [QuantConnect/Lean#4685] opened 2020-09-03 00:30 UTC
#### Expected Behavior
IndicatorExtensions.Of should apply the output of the first indicator as the input of the second indicator in Python Research Notebooks.

#### Actual Behavior
IndicatorExtensions.Of between two indicators, say SimpleMovingAverage and StandardDeviation, only compute the first indicator. Relevant [thread](https://www.quantconnect.com/forum/discussion/9118/potentially-silly-question-on-documentation/p1)

#### Reproducing the Problem

https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_2e57d17a0809c00359118f799bf0e341.html
#### System Information

Web IDE
#### Checklist

- [x ] I have completely filled out this template
- [x ] I have confirmed that this issue exists on the current `master` branch
- [x ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x ] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment] 2020-09-08 13:29
Closing as a duplicate of https://github.com/QuantConnect/Lean/issues/3565

**Closed by Martin-Molinero** 2020-09-08 13:29 UTC
