### ISSUE TITLE
Daily option resolution  (slow options backtest)

### ISSUE THREAD

**Issue by lorrp1** [QuantConnect/Lean#5343] opened 2021-02-25 21:16 UTC
Can someone please start working on daily resolution for options data in quantconnect? 

I tried using consolidation but backtest are still extremely slow.

**Comment by Martin-Molinero** [comment] 2021-04-07 23:58
Duplicate of https://github.com/QuantConnect/Lean/issues/941

**Closed by Martin-Molinero** 2021-04-07 23:58 UTC
