### ISSUE TITLE
Benchmark Receives Raw Data

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#7846] opened 2024-03-12 13:17 UTC
#### Expected Behavior
The benchmark only receives data from one data normalization mode.

#### Actual Behavior

The algorithm subscribes to raw data from BIL:

```python
self.SetStartDate(2014, 1, 1)
self.ticker = 'BIL'
self.equity = self.AddEquity(self.ticker, Resolution.Minute, dataNormalizationMode=DataNormalizationMode.Raw)
self.SetBenchmark("BIL")
```

and the benchmark chart displays an initial value that is about half of the following values:

![result](https://github.com/QuantConnect/Lean/assets/6889033/023f902d-639e-4158-91ab-53da40d40c48)

Here is the raw data (from [results.json](https://github.com/QuantConnect/Lean/files/14572678/results.json)):

![Captura de ecrã 2024-03-11 185724](https://github.com/QuantConnect/Lean/assets/6889033/08935746-4b81-4ef3-9b3f-432be692c8be)

#### Potential Solution
N/A

#### Reproducing the Problem
I cannot reproduce it with the code in "Actual Behavior". The algorithm subscribes to option contracts later in its logic. 

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jhonabreul** [comment] 2024-05-02 16:53
Closing this for the moment since it could not be reproduced

**Closed** 2024-05-09 22:09 UTC
Labels: bug
