### ISSUE TITLE
Python.Runtime.PythonException: TypeError : tzinfo argument must be None or of a tzinfo subclass, not type 'tuple'

### ISSUE THREAD

**Issue by tomhunter-gh** [QuantConnect/Lean#950] opened 2017-05-28 22:14 UTC
I'm getting a PythonNet exception when I try to access the `UtcTime` property of an `OrderEvent` object.

In the **BasicTemplateAlgorithm.py** algorithm, if I add the below print statement after the self.SetHoldings method call then I get a crash:

```python
self.SetHoldings(self.spy, 1)
print self.Transactions.GetOrderTicket(self.Transactions.LastOrderId).OrderEvents[0].UtcTime
```

The full error is:

> 20170528 22:57:23 ERROR:: AlgorithmManager.Run(): RuntimeError: Slice: Python.Runtime.PythonException: TypeError : tzinfo argument must be None or of a tzinfo subclass, not type 'tuple'
>    at Python.Runtime.PyObject.Invoke(PyTuple args, PyDict kw)
>    at Python.Runtime.PyObject.InvokeMethod(String name, PyTuple args, PyDict kw)
>    at Python.Runtime.PyObject.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
>    at CallSite.Target(Closure , CallSite , Object , Slice )
>    at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
>    at QuantConnect.Python.Wrappers.AlgorithmPythonWrapper.OnData(Slice slice) in D:\Users\Tom\Dropbox\Algo Trading\QuantConnect\tomhunter-gh\Lean\AlgorithmFactory\Python\Wrappers\AlgorithmPythonWrapper.cs:line 641
>    at QuantConnect.Lean.Engine.AlgorithmManager.Run(AlgorithmNodePacket job, IAlgorithm algorithm, IDataFeed feed, ITransactionHandler transactions, IResultHandler results, IRealTimeHandler realtime, ICommandQueueHandler commands, CancellationToken token) in D:\Users\Tom\Dropbox\Algo Trading\QuantConnect\tomhunter-gh\Lean\Engine\AlgorithmManager.cs:line 599

I'm pretty sure this was working before the recent commits with regards to Python datetime vs .NET DateTime types..  however I didn't test this exact line of code - this is a simplified test scenario.  

The real scenario I have involves trying to read the UtcTime property in a (Python) handler method for a (.NET) consolidator - in this case I get:

> Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>    at Python.Runtime.Runtime.PyObject_CallObject(IntPtr pointer, IntPtr args)
>    at Python.Runtime.Converter.ToPython(Object value, Type type)
>    at Python.Runtime.FieldObject.tp_descr_get(IntPtr ds, IntPtr ob, IntPtr tp)
>    at Python.Runtime.Runtime.PyObject_Call(IntPtr pointer, IntPtr args, IntPtr kw)
>    at Python.Runtime.Dispatcher.TrueDispatch(ArrayList args)
>    at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
>    at QuantConnect.Data.Consolidators.DataConsolidator\`1.OnDataConsolidated(IBaseData consolidated) in D:\Users\Tom\Dropbox\Algo Trading\QuantConnect\tomhunter-gh\Lean\Common\Data\Consolidators\DataConsolidator.cs:line 101
>    at QuantConnect.Data.Consolidators.MyConsolidator.Update(QuoteBar data) in D:\Users\Tom\Dropbox\Algo Trading\QuantConnect\tomhunter-gh\Lean\Common\Data\Consolidators\MyConsolidator.cs:line 88
>    at QuantConnect.Data.Consolidators.DataConsolidator`1.Update(IBaseData data) in D:\Users\Tom\Dropbox\Algo Trading\QuantConnect\tomhunter-gh\Lean\Common\Data\Consolidators\DataConsolidator.cs:line 39
>    at QuantConnect.Lean.Engine.AlgorithmManager.Run(AlgorithmNodePacket job, IAlgorithm algorithm, IDataFeed feed, ITransactionHandler transactions, IResultHandler results, IRealTimeHandler realtime, ICommandQueueHandler commands, CancellationToken token) in D:\Users\Tom\Dropbox\Algo Trading\QuantConnect\tomhunter-gh\Lean\Engine\AlgorithmManager.cs:line 495
>    at QuantConnect.Lean.Engine.Engine.<>c__DisplayClass8_1.<Run>b__2() in D:\Users\Tom\Dropbox\Algo Trading\QuantConnect\tomhunter-gh\Lean\Engine\Engine.cs:line 256
>    at System.Threading.Tasks.Task.Execute()
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
>    at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()

My assumption is that it's related to the simplified test case but it may not be..

**Comment by AlexCatarino** [comment] 2017-05-29 12:14
Hi @tomhunter-gh, thank you for the bug report.
When I tried to reproduce the issue with the simplified test, I got _System.AccessViolationException_. 
I have already a fix for it and will be included in the next update of our pythonnet fork.

**Comment by tomhunter-gh** [comment] 2017-05-29 12:57
Thanks @AlexCatarino, much appreciated.  What was the fix?

As an aside, I am curious to know the reason for the separate fork of PythonNet.  (I'm sure there are good reasons, but) I see that the fork is now a few hundred commits behind the main project.  Would it be possible to have the QuantConnect specific modifications pushed back into the main project and just have LEAN reference that instead?  Interested to know what your thoughts are.  Thanks

**Comment by AlexCatarino** [comment] 2017-05-29 13:08
The timezone computation was performed only once and store as a class member. Whereas we need to create a new tzinfo object for every new datetime.
We have a different fork, because if we need to make a patch and make it available, we cannot wait pythonnet to incorporate it. We are looking at "rebasing" our fork soon.

**Comment by AlexCatarino** [comment] 2017-06-02 17:20
@tomhunter-gh , PR #954 fixes this issue.
We also updated our pythonnet version to be updated with pythonnet's master.
Please note we changed how we manage the UCS2/UCS4 dlls ([readme](https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/readme.md)).

**Closed** 2017-06-26 18:38 UTC
