### ISSUE TITLE
Runtime statistics access for algorithms

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#2688] opened 2018-11-12 19:37 UTC
#### Expected Behavior
Be able to access runtime statistics (e.g. win rate, sharpe ratio, etc) with the algorithm. 

#### Actual Behavior
Algorithm statistics are calculated at the result handlers and users don't have access to this information during an algorithm execution which may be important for live algorithms.
Link: https://www.quantconnect.com/forum/discussion/3619/better-live-tracking-statistics/p1

#### Potential Solution
N/A

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by michaelsrew** [comment] 2018-12-30 20:03
#1105

**Comment by jaredbroad** [comment] 2018-12-30 21:40
Closing as duplicate of #1105 and transferred details there.

**Closed** 2018-12-30 21:40 UTC
