### ISSUE TITLE
Create New Library defaults to F#

### ISSUE THREAD

**Issue by jcandan** [QuantConnect/Lean#1175] opened 2017-10-01 02:11 UTC
## Problem

When hitting Create New Library, a clone of Basic Library Template (F#) is made, defaulting the Library to F#.

## Expected behavior

Should display a "Create New Library" language-select modal (e.g. C#, Python, F#) similar to the one displayed when creating a new project.

## Reproduce

From an open project, hit Add New Library, then Create New Library.

## Work around

In the meantime, after you hit "Create New Library", you may click the Project Language button, and select your preferred language. Note that you will need to delete the `Main.fs` file that was created.

**Comment by jaredbroad** [comment] 2017-10-01 02:39
Hey James, are you referring to a QuantConnect.com project? If so, library
projects are just projects which live in the library folder. The source is
copied into all compiles

On Sep 30, 2017 10:11 PM, "James Candan" <notifications@github.com> wrote:

Problem

When hitting Create New Library, a clone of Basic Library Template (F#) is
made.
Expected behavior

Should display a "Create New Library" language-select modal similar to the
one displayed when creating a new project.
Reproduce

From an open project, hit Add New Library, then Create New Library.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/QuantConnect/Lean/issues/1175>, or mute the thread

**Comment by jcandan** [comment] 2017-10-01 04:02
Yes, it is for a QuantConnect.com project. The slight problem is that when creating a Project you get the option to select a language, but that option is not given when you hit "Create New Library" from within a project, it simply defaults to F#. I've since added a note about a work-around to the issue which will allow one to change the Project Language, but for keeping with the established UX, I would recommend this fix.

Just an aside, the value of a "Library" folder to me is the ability to have custom python modules that I can make available to my algorithms.

Example:

```
Home/
├── Library/
│   ├──hello_world/
│   │   ├──__init__.py
│   │   └── hello.py
├── MyCoolProject
└── ──Main.py

. . . 

# Main.py
import hello
class BasicTemplateAlgorithm(QCAlgorithm):
    def Initialize(self):
        self.Debug(hello.hello_world())
```

**Comment by jaredbroad** [comment] 2017-10-01 21:38
Cool the intent of the library folder what exactly as you're using it -- to make modules available to other algorithms.  Closing as not a LEAN bug/feature but QuantConnect one.

**Closed by jaredbroad** 2017-10-01 21:38 UTC
