### ISSUE TITLE
Orders Should Take into Account DefaultOrderProperties.OutsideRegularTradingHours

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#6099] opened 2021-12-06 18:46 UTC
#### Expected Behavior
If `DefaultOrderProperties.OutsideRegularTradingHours` is set to false, `Limit` and `StopLimit` orders should not be filled if the subscriptions do not include extended market hours. 

#### Actual Behavior
If `DefaultOrderProperties.OutsideRegularTradingHours` is not taken into account in the Equity Fill Models.

#### Potential Solution
Adds `OrderProperties` to the `FillModelParameters` to process the information from `OutsideRegularTradingHours`.

#### Reproducing the Problem
Initialize algorithm with:
```python
self.symbol = self.AddEquity("SPY", Resolution.Minute, extendedMarketHours = True).Symbol
self.DefaultOrderProperties.OutsideRegularTradingHours = False
```
and place a limit order. It's filled before the market opens.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment] 2023-02-17 15:54
Closing as duplicate of https://github.com/QuantConnect/Lean/issues/3947 where we will solve it generically in the base OrderProperties

**Closed by Martin-Molinero** 2023-02-17 15:54 UTC
Labels: bug, order-types
