### ISSUE TITLE
C# Notebook GetFundamental not functional

### ISSUE THREAD

**Issue by haxdds** [QuantConnect/Lean#4490] opened 2020-06-04 23:13 UTC
#### Expected Behavior

[qb.GetFundamental(tickers, selector, start, end)](https://github.com/QuantConnect/Lean/blob/master/Research/QuantBook.cs#L151) should return fundamental data for given tickers.
#### Actual Behavior

[qb.GetFundamental(tickers, selector, start, end)](https://github.com/QuantConnect/Lean/blob/master/Research/QuantBook.cs#L151) does not accept any valid input for `PyObject tickers`.  

When using `var history = qb.GetFundamental(qb.Securities.Keys, "ValuationRatios.PERatio", start, end);` 

A `System.Collections.Generic.ICollection<QuantConnect.Symbol>'expression to type Python.Runtime.PyObject` error is thrown.
#### Potential Solution

N/A
#### Reproducing the Problem

See [thread](https://www.quantconnect.com/forum/discussion/8302/how-to-get-fundamental-data-in-c-sharp-notebook/p1). Also running `var history = qb.GetFundamental(qb.Securities.Keys, "ValuationRatios.PERatio", start, end)`
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment] 2020-06-04 23:15
Duplicate of #4487

**Closed by AlexCatarino** 2020-06-04 23:15 UTC
