### ISSUE TITLE
System.AccessViolationException referencing self.UtcTime in .py

### ISSUE THREAD

**Issue by se-l** [QuantConnect/Lean#1079] opened 2017-08-21 03:24 UTC
When referencing **self.UtcTime** in .OnData, I always receive a

_**System.AccessViolationException**: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'_

like in this issue @AlexCatarino  : #950 
I cloned the master branch repos last week. Is there a chance I missed the fix?

Below a forex variation of BasicTemplateAlgorithm.py, that reproduces the error for me. Tried reproducing it in the browser IDE, but would get stuck 'waiting for results' / 'analyzing' not returning results. Works fine with self.Time

Happy to provide more details. First time use of .NET / VS for quantconnect.

`from clr import AddReference
AddReference("System")
AddReference("QuantConnect.Algorithm")
AddReference("QuantConnect.Common")

from System import *
from QuantConnect import *
from QuantConnect.Algorithm import *
import decimal as d

class BasicTemplateAlgorithm(QCAlgorithm):
    '''Basic template algorithm simply initializes the date range and cash'''

    def Initialize(self):
        '''Initialise the data and resolution required, as well as the cash and start-end dates for your algorithm. All algorithms must initialized.'''
        
        self.SetStartDate(2017,1,10)  #Set Start Date
        self.SetEndDate(2017,1,17)    #Set End Date
        self.SetCash(100000)           #Set Strategy Cash
        # Find more symbols here: http://quantconnect.com/data
        self.AddForex("EURUSD", Resolution.Minute)

    def OnData(self, data):
        '''OnData event is the primary entry point for your algorithm. Each new data point will be pumped in here.
        
        Arguments:
            data: Slice object keyed by symbol containing the stock data
        '''
        newTicket = self.MarketOrder("EURUSD", 1000 )
        #print newTicket.Time#self.Transactions.GetOrderTicket(self.Transactions.LastOrderId).OrderEvents[0].UtcTime
        print self.UtcTime
        #print self.Time`

Goal is to subtract current time and order Time.
For now, I would continue using self.Time with a workaround. Since the order tz and self.Time tz have an offset of 4h, I thought it's best to use Utc. Will adjust time (+4) or adjust time zones until I figure out what's wrong. Appreciating any hints....

Full error:
`		StackTrace	"   at Python.Runtime.Runtime.PyImport_ExecCodeModule(String name, IntPtr code)\r\n   at Python.Runtime.PythonEngine.ModuleFromString(String name, String code)\r\n   at Python.Runtime.Converter.TzInfo(Int32 hours, Int32 minutes)\r\n   at Python.Runtime.Converter.ToPython(Object value, Type type)\r\n   at Python.Runtime.PropertyObject.tp_descr_get(IntPtr ds, IntPtr ob, IntPtr tp)\r\n   at Python.Runtime.Runtime.PyObject_Call(IntPtr pointer, IntPtr args, IntPtr kw)\r\n   at Python.Runtime.PyObject.Invoke(PyTuple args, PyDict kw)\r\n   at Python.Runtime.PyObject.InvokeMethod(String name, PyTuple args, PyDict kw)\r\n   at Python.Runtime.PyObject.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)\r\n   at CallSite.Target(Closure , CallSite , Object , Slice )\r\n   at QuantConnect.AlgorithmFactory.Python.Wrappers.AlgorithmPythonWrapper.OnData(Slice slice) in C:\\repos\\QuantConnect2\\Lean\\AlgorithmFactory\\Python\\Wrappers\\AlgorithmPythonWrapper.cs:line 662\r\n   at QuantConnect.Lean.Engine.AlgorithmManager.Run(AlgorithmNodePacket job, IAlgorithm algorithm, IDataFeed feed, ITransactionHandler transactions, IResultHandler results, IRealTimeHandler realtime, ILeanManager leanManager, CancellationToken token) in C:\\repos\\QuantConnect2\\Lean\\Engine\\AlgorithmManager.cs:line 584\r\n   at QuantConnect.Lean.Engine.Engine.<>c__DisplayClass8_1.<Run>b__2() in C:\\repos\\QuantConnect2\\Lean\\Engine\\Engine.cs:line 251\r\n   at System.Threading.Tasks.Task.Execute()\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)\r\n   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)\r\n   at System.Threading.ThreadPoolWorkQueue.Dispatch()"	string
`

**Comment by se-l** [comment] 2017-08-23 05:33
reproduced with pythonnet [repo aug23](https://github.com/QuantConnect/pythonnet/commit/8f4dfe15914693712111fa7e1dadba19285e5143) and rebuild solution. same for anyone else?

**Comment by jaredbroad** [comment] 2017-08-23 12:01
@se-l we're aware of issue and are working on a fix. Its likely a dupe of #1031.

**Comment by jaredbroad** [comment] 2017-09-13 19:52
Fixed by #1127

**Closed by jaredbroad** 2017-09-13 19:52 UTC
Labels: bug
