### ISSUE TITLE
Review DonchianChannel Indicator Calculation

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4278] opened 2020-04-03 22:50 UTC
#### Expected Behavior
`DonchianChannel` indicator does not have a lag. 

#### Actual Behavior
`DonchianChannel` indicator has a lag:
```csharp
        protected override decimal ComputeNextValue(IBaseDataBar input)
        {
            if (_previousInput != null)
            {
                UpperBand.Update(_previousInput.Time, _previousInput.High);
                LowerBand.Update(_previousInput.Time, _previousInput.Low);
            }

            _previousInput = input;
            return (UpperBand + LowerBand) / 2;
        }
```
it's not clear why we are using previous input to calculate the bands. It is consistent with the results of third-party software, but not with formulae that can be found online.

#### Potential Solution
Remove the lag:
```csharp
        protected override decimal ComputeNextValue(IBaseDataBar input)
        {
            UpperBand.Update(input.Time, input.High);
            LowerBand.Update(input.Time, input.Low);
            return (UpperBand + LowerBand) / 2;
        }
```
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by adriantorrie** [comment] 2020-04-30 11:19
Richard Donchian included the lag, because the momentum signal is triggered by:
- the current bar closing above/below the high/low of the previous `n` periods
- the current bar moving through above/below the high/low of the previous `n` periods.

If immediate updates occur, the close can never be above/below the channel, nor can price move through the channel intra-period, as immediate updates would mean the price can only ever be:
 - Upper prices will be always be `<=` upper band, and never `>` (which is needed for a signal).
- Lower prices will always be `>=` the lower band, and never `<` (which is needed for a signal).

**Comment by jaredbroad** [comment] 2023-02-17 14:39
- Review regression data and see if we have a good test set.
 - See if we still pass tests with the new regression data applied. 
 - If don't pass tests; review indicator code to fix.

**Closed** 2023-06-21 18:26 UTC
Labels: bug, indicator, good first issue, depth, impact-low

**Comment by Martin-Molinero** [comment] 2023-06-21 18:31
We've updated Lean to match other trading platforms for the DonchianChannel indicator calculation.

> Richard Donchian included the lag, because the momentum signal is triggered by:
> 
> * the current bar closing above/below the high/low of the previous `n` periods
> * the current bar moving through above/below the high/low of the previous `n` periods.
> 
> If immediate updates occur, the close can never be above/below the channel, nor can price move through the channel intra-period, as immediate updates would mean the price can only ever be:
> 
> * Upper prices will be always be `<=` upper band, and never `>` (which is needed for a signal).
> * Lower prices will always be `>=` the lower band, and never `<` (which is needed for a signal).

@adriantorrie the case you mention could happen if the resolution of the indicator matches the resolution of the data feed, you can easily get the previous value of the lower/upper bands with `UpperBand[1]` & `LowerBand[1]` in your code.
