### ISSUE TITLE
Oanda Market Hours for EURUSD should be UTC

### ISSUE THREAD

**Issue by jameschch** [QuantConnect/Lean#757] opened 2017-02-20 12:39 UTC
There is one market hours rule for all Oanda Forex (America/New York), however, the EURUSD pair is returned with a UTC timestamp, causing all ticks to be ignored in FrontierAwareEnumerator. I imagine this  may also be the case for other forex pairs not denominated in USD.

**Comment by jameschch** [comment] 2017-02-20 13:09
The logic makes sense in backtests to prevent look ahead bias. I'm not sure this is as essential in live mode. It would be useful to have a warning that data is being dropped, so I have a version running with this:
```

            if (underlyingCurrent != null && underlyingCurrent.Symbol.ID.Market != "empty")
            {
                _needsMoveNext = true;
                _current = underlyingCurrent;
                //tolerate 90 second timeslip between local and data. Otherwise warn.
                if (underlyingCurrent.EndTime > localFrontier.AddSeconds(90))
                {
                    Logging.Log.Error("Data timestamp was later than local. Check the markets hours: " + underlyingCurrent.Symbol.ToString());
                }
            }
            else
            {
                _current = null;
                _needsMoveNext = underlyingCurrent == null;
            }
```

**Comment by jaredbroad** [comment] 2017-02-20 13:33
Hey @jameschch; we distinguish between data and exchange timezone. The backtest and live streams from them are in UTC, but most people work on EST for FX (we convert it to EST). Are you seeing backtest or live streaming data in EST?
```
"Forex-oanda-[*]": {
      "dataTimeZone": "UTC",
      "exchangeTimeZone": "America/New_York",
```

**Comment by jameschch** [comment] 2017-02-20 14:11
I'm seeing raw tick data on live in UTC. I have only noticed this so far on EURUSD. If I change the exchangeTimeZone to UTC, the ticks are passed through to the algorithm via event handlers as normal.

**Comment by jameschch** [comment] 2017-02-20 14:18
Beyond that, I have also added a new rule for this pair:
```

	"Forex-oanda-EURUSD": {
            "dataTimeZone": "UTC",
            "exchangeTimeZone": "UTC",
            "monday": [
                {
                    "start": "00:00:00",
                    "end": "1.00:00:00",
                    "state": "market"
                }
            ],
            "tuesday": [
                {
                    "start": "00:00:00",
                    "end": "1.00:00:00",
                    "state": "market"
                }
            ],
            "wednesday": [
                {
                    "start": "00:00:00",
                    "end": "1.00:00:00",
                    "state": "market"
                }
            ],
            "thursday": [
                {
                    "start": "00:00:00",
                    "end": "1.00:00:00",
                    "state": "market"
                }
            ],
            "friday": [
                {
                    "start": "00:00:00",
                    "end": "1.00:00:00",
                    "state": "market"
                }
            ],
            "saturday": [ ],
            "sunday": [ ],
            "holidays": [ ]
        },
```

However, I've not tested how many other pairs are affected. I'm willing to accept this is an issue with just this pair on just my account, but am not able to verify this.

**Comment by jaredbroad** [comment] 2017-02-20 14:19
Interesting. Above *"we convert it to EST" - I mean we convert it to AlgorithmTimeZone which is EST for most people. Exchange timezone is the time zone for the market open and close hours which is correct;
```
      "exchangeTimeZone": "America/New_York",
      "sunday": [
        {
          "start": "17:00:00",
          "end": "1.00:00:00",
          "state": "market"
        }
      ],
     ....
           "friday": [
        {
          "start": "00:00:00",
          "end": "17:00:00",
          "state": "market"
        }
      ],
```
i.e. Oanda's market hours (https://oanda.secure.force.com/AnswersSupport?language=en_US&urlName=Hours-of-Operation-1436196464451) are roughly 5pm Friday -> 5pm Sunday.

Potentially you're seeing a bug somewhere else as a by product of your local timezone? What timezone are you locally working in?

**Comment by jameschch** [comment] 2017-02-20 14:36
Have recreated this on a windows desktop on BST as well as a linux datacentre in NY. This was my initial suspicion: it must be the local timezone, but don't see why just this one pair is affected. I'm not explicitly setting a timezone in the algorithm, but did try this earlier when trying to diagnose the problem.

I don't see the date being converted between the raw tick with a Zulu timestamp and the check in the FrontierAwareEnumerator comparing UTC to localFrontier.

Maybe this is only for accounts registered in Europe.

**Comment by StefanoRaggi** [comment] 2017-03-20 20:38
Hi @jameschch,
the time zone issue you were experiencing should be fixed by this PR (merged today): https://github.com/QuantConnect/Lean/pull/807

When you have time, can you please check if the issue is resolved, so we can close it ?

**Comment by jameschch** [comment] 2017-03-20 21:11
Excellent. Will take a look as soon as I can.

On 20 March 2017 20:38:47 GMT+00:00, Stefano Raggi <notifications@github.com> wrote:

Hi @jameschch<https://github.com/jameschch>,
the time zone issue you were experiencing should be fixed by this PR (merged today): #807<https://github.com/QuantConnect/Lean/pull/807>

When you have time, can you please check if the issue is resolved, so we can close it ?

**Comment by jameschch** [comment] 2017-03-22 20:15
Thanks for looking into this, I can see the ticks feed through on EURUSD with a utc timestamp using the current build.

**Closed** 2017-03-22 20:19 UTC

**Comment by StefanoRaggi** [comment] 2017-03-22 20:47
Oanda ticks come in from the Oanda REST API as UTC, but now should always be converted by OandaBrokerage DataQueueHandler to the configured ExchangeTimeZone:
https://github.com/QuantConnect/Lean/blob/master/Brokerages/Oanda/OandaBrokerage.DataQueueHandler.cs#L246

The default value for all Forex symbols in the current market-hours-database is America/NewYork:
```
"Forex-oanda-[*]": {
      "dataTimeZone": "UTC",
      "exchangeTimeZone": "America/New_York",
```

Are you still using the market-hours rule for EURUSD you posted above ?

**Comment by jameschch** [comment] 2017-03-22 21:22
I'm testing with the current master build including config files. When I say ticks are coming through as UTC, I mean in the FrontierAwareEnumerator (which had the switch causing the previous error). In the algorithm the time is converted to NY as expected.
