### ISSUE TITLE
Q: is this abug? MACD indicator receive the raw tick instead of the consolidate 1-min bar?

### ISSUE THREAD

**Issue by mingwugmail** [QuantConnect/Lean#4273] opened 2020-04-03 16:35 UTC
#### Expected Behavior

I used something similar to this:
https://github.com/QuantConnect/Lean/blob/master/Algorithm.CSharp/WarmupIndicatorRegressionAlgorithm.cs#L53

but using a TickConsolidator to consolidate ticks into 1-min bar:
```
      _nMinuteConsolidator = new TickConsolidator(TimeSpan.FromMinutes(_AGG_MINUTE_N));

      _algo.RegisterIndicator(_symbol,  _ema13, _nMinuteConsolidator);
      _algo.RegisterIndicator(_symbol,   _macd, _nMinuteConsolidator);
      _algo.RegisterIndicator(_symbol,   _fast, _nMinuteConsolidator);
      _algo.RegisterIndicator(_symbol, _middle, _nMinuteConsolidator);
      _algo.RegisterIndicator(_symbol,   _slow, _nMinuteConsolidator);
      _algo.RegisterIndicator(_symbol,    _atr, _nMinuteConsolidator);

```
However, in testing I got error message like this:
```
20200403 12:27:04.843 ERROR:: This is a forward only indicator: MACD(12,26,9,MAR_tick) Input: 2020-04-03 12:26:58Z Previous: 2020
-04-03 12:27:00Z. It will not be updated with this input.
```

As you can see I also have many other indicators, MACD is the only one that have this kind of error message.

#### Actual Behavior
From the error message, looks like MACD is receiving tick data instead of the consolidate 1-min bar?

Is this a bug? Why only MACD report such error message?

Anything I can try to verify if this is a bug or not?

Thanks.

**Comment by Martin-Molinero** [comment] 2020-05-12 22:44
Hey @mingwugmail! 
I tested with the following algorithm and was unable to reproduce the reported issue, mind providing a simple algorithm which has the reported behavior? Thanks!
```
public class ParticleTachyonReplicator : QCAlgorithm
{
    public override void Initialize()
    {
        SetStartDate(2020, 04, 03);
        SetEndDate(2020, 04, 04);
        SetWarmup(TimeSpan.FromDays(1));

        var spy = AddEquity("SPY", Resolution.Tick).Symbol;

        var consolidator = new TickConsolidator(TimeSpan.FromMinutes(1));
        var sma = new MovingAverageConvergenceDivergence("MACD", 12, 26, 9);
        consolidator.DataConsolidated += (sender, bar) =>
        {
            Plot("MACD", "Signal", sma.Signal);
            Plot("MACD", "Slow", sma.Slow);
            Plot("MACD", "Fast", sma.Fast);
        };
        RegisterIndicator(spy, sma, consolidator);
    }
}
```

**Comment by jaredbroad** [comment] 2020-06-25 18:54
Closing as not repeatable

**Closed by jaredbroad** 2020-06-25 18:54 UTC
