### ISSUE TITLE
Add a warning message when a user uses daily data and schedules intraday events during a backtest

### ISSUE THREAD

**Issue by HalldorAndersen** [QuantConnect/Lean#2970] opened 2019-02-27 19:09 UTC
#### Expected Behavior
Add a warning message when a user uses daily data and schedules intraday events during a backtest.

#### Actual Behavior
A scheduled intraday event during backtest results, while using daily data, does not produce a warning message, which can result in no available data for added securities at the time of the scheduled event.

#### Potential Solution
Add a warning message when the data resolution used for a scheduled event is higher than for user data.

#### Reproducing the Problem
``` python
self.UniverseSettings.Resolution = Resolution.Daily
self.spy = self.AddEquity("SPY", Resolution.Daily)
self.Schedule.On(self.DateRules.EveryDay("SPY"), self.TimeRules.AfterMarketOpen("SPY", 60), Action(self.Market))
```

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment] 2019-11-06 18:53
Duplicate of https://github.com/QuantConnect/Lean/issues/3687

**Closed by Martin-Molinero** 2019-11-06 18:53 UTC
