### ISSUE TITLE
Logging.WhoCalledMe.GetMethodName NullReferenceException

### ISSUE THREAD

**Issue by DummyCo** [QuantConnect/Lean#2156] opened 2018-06-24 22:16 UTC
Hi there! While trying to acquire historical data from _Oanda_ with next parameters:
`./QuantConnect.ToolBox EURUSD Minute 20100101 20180101`
I've got next exception after a couple of execution hours:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at QuantConnect.Logging.WhoCalledMe.GetMethodName(Int32 frame) in \Lean\Logging\WhoCalledMe.cs:line 36
   at QuantConnect.ToolBox.OandaDownloader.Program.Main(String[] args) in \Lean\ToolBox\OandaDownloader\Program.cs:line 102
```

#### Potential Solution
Looks like _new StackFrame(frame + 1).GetMethod()_ returns null somehow and actual exception is lost because of error in logging pipeline.

#### Reproducing the Problem
No stable attempts to reproduce

#### System Information
Windows 10

Thank you!

**Comment by mchandschuh** [comment] 2018-06-24 22:18
Interesting. This method should only be invoked via the log handler. I notice that the log handler isn't in that stack. Given the stack it makes sense, since +1 would put it above main. This MIGHT be the jit inlining the log method, but unlikely, I don't think it will inline interface methods. Given the stack it looks like the method was called directly from main which it isn't designed to do. If we can't reproduce this then I suggest we close it.

**Comment by mchandschuh** [comment] 2018-06-24 22:45
Did you make any edits to the code? If not, then we may need to add attributes to suppress jit inlining.

**Comment by DummyCo** [comment] 2018-06-24 22:56
@mchandschuh no changes made

**Comment by mchandschuh** [comment] 2018-06-24 23:05
Roger that.

Let's add attributes to suppress method inlining on all methods that call into WhoCalledMe.

**Closed** 2018-07-31 14:41 UTC
Labels: bug
