### ISSUE TITLE
Broken PDF Report Generation 

### ISSUE THREAD

**Issue by marvin-hansen** [QuantConnect/Lean#3617] opened 2019-09-26 09:34 UTC
#### Affected Version

LEAN: master (v6343)
Hash: 45ffbb393f
Released: 2019-09-25 22:18:23

#### Expected Behavior

When clicking Download Report, a PDF should appear. 

#### Actual Behavior

A white page appears with the following error message:

U n d e fin e d in d e x: H TT P _ X _ R E A L_IP in / v a r / w w w / m a s t e r / c o r e / c o n t r olle r s / cla s s.e r r o r.r e p o r tin g.p h p

Screenshot attached. 

![Error Message](https://user-images.githubusercontent.com/24190940/65677218-829fe300-e051-11e9-983c-c7b537cc51f2.png)

#### Reproducing the Problem
I have the same issue across all algos, whenever I try to download a PDF report, I get one and the same error. 

#### System Information
Client: Win 10 / Chrome 

#### Checklist

- [ X] I have completely filled out this template
- [ X] I have confirmed that this issue exists on the current `master` branch
- [ X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ X] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment] 2019-10-03 23:53
Hi @marvin-hansen,
I couldn't reproduce the issue with the `BasicTemplateAlgorithm`. 
Is it still an issue for your projects?

Closing because it is not a Lean issue. Please report bugs to support@quantconnect.com or [QC Slack channel](https://www.quantconnect.com/slack).

**Closed by AlexCatarino** 2019-10-03 23:53 UTC
