### ISSUE TITLE
History in research crashes kernel if it cannot find the symbol

### ISSUE THREAD

**Issue by Worthy7** [QuantConnect/Lean#1114] opened 2017-09-04 08:01 UTC
`qb.AddEquity("MBSP")
qb.History("MBSP", 40, Resolution.Minute)`

Not sure how one is supposed to filter by exchange either, but regardless, an error message would be nice.

**Comment by AlexCatarino** [comment] 2018-01-08 18:50
@Worthy7, I couldn't reproduce the issue. It was probably fixed by some work we have done on QuantBook. When there is no data, an empty pandas DataFrame is returned.

**Closed by AlexCatarino** 2018-01-08 18:50 UTC
Labels: bug
