### ISSUE TITLE
Upgrade Visual Studio solution/project version?

### ISSUE THREAD

**Issue by phatcher** [QuantConnect/Lean#3948] opened 2019-12-30 19:45 UTC
Any plans to upgrade the VS version so the platform could support .NET Core etc?

Paul

**Comment by Martin-Molinero** [comment] 2020-12-07 20:38
Hey!
Yes 💯  it's in the plans. Closing as duplicate of https://github.com/QuantConnect/Lean/issues/1686

**Closed by Martin-Molinero** 2020-12-07 20:38 UTC
