### ISSUE TITLE
Some trading pairs in Binance are not recognized

### ISSUE THREAD

**Issue by jimmychu0807** [QuantConnect/Lean#8207] opened 2024-07-18 04:27 UTC
Some trading pairs in Binance are not recognized, including [ALT/USDT](https://www.binance.com/en/trade/ALT_USDT) and [STRK/USDT](https://www.binance.com/en/trade/STRK_USDT). I am sure there are more.

#### Actual Behavior
When I initialize my quantconnect algo to my Binance account, which holds ALTUSDT, it returns the following error:

![Screenshot_2024-07-18_at_11 38 17](https://github.com/user-attachments/assets/041809ad-8339-452c-858b-787513c3b35a)

When I explicitly `add_crypto()` inside the `__initialize__()` constructor, it returns:

![Screenshot_2024-07-18_at_11 47 46](https://github.com/user-attachments/assets/2e2f510f-3942-44f1-93fb-313ef7af7043)

#### Expected Behavior
I would expect these trading pairs are supported inside Quantconnect.

#### Potential Solution
- short-term: Adding these two tickers to [symbol-properties-database.csv](https://github.com/QuantConnect/Lean/blob/master/Data/symbol-properties/symbol-properties-database.csv)
- a better solution: is there a way to write a script to pull all trading pairs from Binance and import them in the csv, and then we run it once a day?

I am happy to investigate this if core dev team is okay with this suggestion and willing to support it.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment] 2024-07-19 22:51
Yes, will close as duplicate of https://github.com/QuantConnect/Lean/issues/6469

**Closed by Martin-Molinero** 2024-07-19 22:51 UTC
