### ISSUE TITLE
Update dotnet framework version to 5.0

### ISSUE THREAD

**Issue by thasmin** [QuantConnect/Lean#5368] opened 2021-03-08 01:43 UTC
#### Expected Behavior
Macos and Linux can't use the current required framework version 4.6.2. Compiling a DLL on these systems makes it incompatible with the current Lean codebase.

#### Actual Behavior
Using an algorithm compiled with dotnet 5.0 should work fine.

#### Potential Solution
Upgrade the target framework to net50.

#### Reproducing the Problem
Compile an algorithm in a DLL with dotnet 5.0. Run Lean with it using either the dockerized or compiled versions. Get an error saying the type id can't be found (or something like that, it's on my other computer).

#### System Information
Macos, dotnet installed with homebrew.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

I understand this may involve a lot of testing and deployment changes to quantconnect.com so there's for you guys to consider. If this is something that the project wants to do, they someone can use and build upon my PR.

**Comment by jaredbroad** [comment] 2021-03-08 02:01
Duplicate of https://github.com/QuantConnect/Lean/issues/452

**Closed by jaredbroad** 2021-03-08 02:01 UTC
