### ISSUE TITLE
QCAlgorithm.Indicators.cs bug in Generic RegisterIndicator

### ISSUE THREAD

**Issue by mirinio** [QuantConnect/Lean#4582] opened 2020-07-18 09:13 UTC
#### Expected Behavior
QCAlgorithm.Indicators.cs  
public void RegisterIndicator<T>(Symbol symbol, IndicatorBase<T> indicator, IDataConsolidator consolidator, Func<IBaseData, T> selector = null)
            where T : IBaseData

code line 1923

Use selector in Register above mentioned RegisterIndicator Method.

#### Actual Behavior
RegisterIndicator mentioned above doesnt use the selector when you use a object T which derives from IndicatorDataPoint and throws an exception. also SelectorToUse var is never null.

#### Potential Solution
either remove var SelectorToUse variable and add an if else to cover the user defined selector or remove the If statement  which creates a normal selector again.

Also ArgumentException thrown there is absolutly wrong.

#### Reproducing the Problem

Create a Class which derives from IndicatorDataPoint and initialise any Indicator with the selector parameter you want.

#### System Information
Exception which is thrown is wrong. its hard to tell but it looks like this:
    throw new ArgumentException($"Type mismatch found between consolidator and indicator for symbol: {symbol}." +
                                                $"Consolidator outputs type {consolidator.OutputType.Name} but indicator expects input type {type.Name}"
                    );

#### Checklist

- [x] I have completely filled out this template
- [x ] I have confirmed that this issue exists on the current `master` branch
- [x ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x ] I have provided detailed steps to reproduce the issue

**Comment by C-SELLERS** [comment] 2020-07-27 22:59
Hey @mirinio could you comment a snippet of code you used that would reproduce this issue? Thank you!

**Comment by Martin-Molinero** [comment] 2020-09-15 15:24
Hey @mirinio, closing this issue for now since we tried but weren't able to reproduce. Feel free to reopen providing a code snippet to reproduce it. Thanks!

**Closed by Martin-Molinero** 2020-09-15 15:24 UTC
