### ISSUE TITLE
Quote data not documented in  README

### ISSUE THREAD

**Issue by id3283** [QuantConnect/Lean#5291] opened 2021-02-11 19:00 UTC
The /Data/equity/README.md file doesn't discuss quote file formats.  The documentation suggests that QuoteBars are built from tick data but neither the tick quote data files nor the second quote files are documented.  Examples of such files include:
 
Data/equity/usa/tick/spy/20131010_quote.zip
Data/equity/usa/second/spy/20131010_quote.zip

The format for the tick quote file is pretty obvious, but the second (bar) quote format is not.  It would be helpful if this format was documented in the README as the trade file format is.

Thanks!

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment] 2021-02-12 20:08
Duplicate of https://github.com/QuantConnect/Lean/issues/5135. Thanks for reporting though!

**Closed by Martin-Molinero** 2021-02-12 20:08 UTC
