### ISSUE TITLE
Backtest gives number overflow from PortfolioStatistics

### ISSUE THREAD

**Issue by chrisdk2015** [QuantConnect/Lean#184] opened 2015-10-07 08:14 UTC
Possibly a mono/Linux issue.

In https://github.com/QuantConnect/Lean/blob/master/Common/Statistics/PortfolioStatistics.cs#L178 I placed a breakpoint.

On my machine using the attached algorithm the code enters line 178 twice. Once with correct values, next time fractionOfYears becomes zero and you get number overflow because of divide by zero later on.

Algorithm:

https://drive.google.com/file/d/0B95K6AyeZ37SNUtJejdqcUlVbm8/view?usp=sharing

data file:

https://drive.google.com/file/d/0B95K6AyeZ37SdzhLYjVDN292SG8/view?usp=sharing

a daily equity usa file

Not sure why it enters the code twice, also not sure why fractionOfYears becomes zero second time.

**Comment by chrisdk2015** [comment] 2015-10-22 08:04
In PortfolioStatistics.cs I have added a check for zero years

```
private static decimal CompoundingAnnualPerformance(decimal startingCapital, decimal finalCapital, decimal years)
{
	if (years != 0)
		return (decimal)Math.Pow ((double)finalCapital / (double)startingCapital, (1 / (double)years)) - 1;
	else
		return 0m;
}
```

which seems it makes it work. At least this doesn't divide by zero then.

**Comment by StefanoRaggi** [comment] 2015-10-24 22:01
@chrisdk2015 

I tested your algorithm and data on Windows and was not able to reproduce the error even when the variable fractionOfYears is zero. According to [MSDN](https://msdn.microsoft.com/en-us/library/6a71f45d(VS.80).aspx) a double division by zero never throws an exception, but returns Infinity.

The reason why the function is called multiple times (740 times in your case) is that StatisticsBuilder.Generate also calculates rolling statistics (for all 1,3,6,12 month periods in your backtest period, 15+ years).

Depending on the algorithm StartDate and EndDate, it could happen that a rolling period only includes one day and this is when fractionOfYears becomes zero.

Anyway, I have submitted a PR with the zero check as you suggested above.

**Comment by mchandschuh** [comment] 2015-10-24 22:36
Merged in https://github.com/QuantConnect/Lean/commit/52dfe34b867558256b455203a2c5ec07251d2ff9

**Closed by mchandschuh** 2015-10-24 22:36 UTC

**Comment by bizcad** [comment] 2015-10-25 04:49
I downloaded the algorithm and ran it in [assembly: AssemblyVersion("2.1.4.2")]  of the Engine.  

I had to add a reference to QuantConnect.Algorithm.CSharp for Math.Net to get it to compile.

I got 579 calls to CompoundingAnnualPerformance, and no Exception thrown.  Windows 10 VS 2013 Community.  I used my GoogleFinance download of daily data.

When I ran it in last Thursday's version [assembly: AssemblyVersion("2.1.5.1")] it called CompoundingAnnualPerformance the same 579 times and no Exception thrown.

Nick

**Comment by chrisdk2015** [comment] 2015-10-25 16:57
Ok, on Mono/Linux a clean program that just divides a double with double zero also gives infinity.

For a decimal it gives a DivideByZero exception.

Maybe something else is going on in Mono that triggers the number overflow possibly a memory corruption somewhere but who knows.
