### ISSUE TITLE
ImmediateFillModel can have unrealistic fill prices for stop market orders

### ISSUE THREAD

**Issue by bhamer** [QuantConnect/Lean#4545] opened 2020-06-28 22:32 UTC
#### Current stop market fill price logic, for reference:
For a buy stop market order (vice versa for sell stops), fill price is the maximum of:
1. Stop price (no slippage applied)
2. Current bar's close + slippage

### Scenario 1
1. Buy stop market order is entered with stop price of 10
2. Current bar opens at 8 and closes at 12, triggering the stop order to be filled

**Expected:** Fill price = 10 + slippage (because the price opened below the stop price and presumably moved through it during the current bar's time period)

**Actual:** Fill price = 12 + slippage (this introduces 20% additional slippage, on top of the existing slippage model, that likely would not have been realized)

### Scenario 2
1. Buy stop market order is entered with stop price of 10
2. Current bar opens at 12 and closes at 8, triggering the stop order to be filled

**Expected:** Fill price = 12 + slippage (because the bar "gap" opened higher than the stop price, which would trigger the stop to be filled at the open)

**Actual:** Fill price = 10 (in reality this would have filled around 12 since that was the open price when the order triggered, so this is effectively introducing negative slippage, in addition to not applying the actual slippage model)

### Potential Solution
Change stop market fill price logic to:
1. If the current bar "passes through" the stop price, fill price = stop price +- slippage
2. If the current bar "gaps" open beyond the stop price, fill price = open price +- slippage

I believe this fill price logic models reality more closely than the existing logic. And it could reduce confusion on where slippage is coming from. When I was initially seeing strange differences between fill and stop prices I assumed it was the slippage model. So I implemented a custom slippage model to reduce it to 0. To my surprise, this had no impact on the large slippage figures I was seeing on stop orders when the price was clearly moving through the stop prices.

One potential issue with this logic is long-interval bars that have price "gaps" within them, e.g., weekly or monthly bars. In this case it's not always safe to assume the price passed through the stop price. But I think making that assumption is, on average, much more realistic than taking the close price or stop price at the end of the bar interval.

### Reproducing the Problem
See examples above.

### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment] 2023-02-17 12:11
Closing as duplicate of this wider fill model review; https://github.com/QuantConnect/Lean/issues/4567#issuecomment-1434534184

**Closed by jaredbroad** 2023-02-17 12:11 UTC
