### ISSUE TITLE
Why is only USD supported as the account currency?

### ISSUE THREAD

**Issue by badokun** [QuantConnect/Lean#4147] opened 2020-03-01 02:40 UTC
https://github.com/QuantConnect/Lean/blob/18664885308ba08d9e44ff5ba602e85f94ba0225/Engine/Setup/BrokerageSetupHandler.cs#L222

I'm currently looking at implementing Bitmex alongside the other crypto exchanges, however Bitmex uses BTC as the accounting currency.

I suspect many of the calculations may need to be inversed, but would appreciate if someone can comment on why this restriction was put in place, and what effort would be required to implement alternative accounting currencies

**Comment by nazbrok** [comment] 2020-03-01 21:28
I think they have a project named Internationalization for this [https://github.com/QuantConnect/Lean/projects](https://github.com/QuantConnect/Lean/projects)

No idea when they plan to finish it though, I also wait after it to be able to margin trade crypto. But crypto doesn't seems to be a high priority

**Comment by jaredbroad** [comment] 2020-03-03 19:58
Closing this as its a duplicate of https://github.com/QuantConnect/Lean/issues/110

It's a hard project which we are aware of is in demand. The account currency is also standing in the way of merging the open PR for Binance https://github.com/QuantConnect/Lean/pull/3511

We don't have the internal bandwidth but are happy to employ consultants focused on moving this specific project along if there are people up to the challenge! If interested shoot me an email jared@quantconnect.com with your background.

**Closed by jaredbroad** 2020-03-03 19:58 UTC
