### ISSUE TITLE
Improves Warning Message for Scheduled Events

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#3687] opened 2019-10-08 16:46 UTC
#### Expected Behavior
Notify users that Scheduled Events needs data with a proper resolution to be triggered at desired moments.

#### Actual Behavior
No message. 

#### Potential Solution
In `TimeRules` class, verify whether the time rule interval and the security highest resolution are compatible. If not, log a message.

#### Reproducing the Problem
The following algorithm should warm (throw an exception?) the user that the data resolution (Daily) is incompatible with intraday scheduled event (need minute resolution or higher in this case)

```csharp
namespace QuantConnect.Algorithm.CSharp {
    public class ScheduledEventsAlgorithm : QCAlgorithm {
        public override void Initialize() {
    	    SetStartDate(2013, 10, 7);
    	    SetEndDate(2013, 10, 11);
            AddEquity("SPY", Resolution.Daily);

            Schedule.On(DateRules.EveryDay("SPY"), TimeRules.AfterMarketOpen("SPY", 10), () => {
                Debug($"IsWarmingUp? {IsWarmingUp}");
            });
        }
    }
}
```
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment] 2019-11-06 18:46
Potential duplicate of https://github.com/QuantConnect/Lean/issues/2970

**Comment by jaredbroad** [comment] 2020-06-23 17:20
Let's post a clear example algorithm showing the red/fail-case for this one.

**Comment by jaredbroad** [comment] 2023-02-17 16:50
- Closing as documented;
 - Closing as orders are flagged with "stale price" warning.

**Closed by jaredbroad** 2023-02-17 16:50 UTC
