### ISSUE TITLE
Deserialization error with null estimated-value of SerializedInsight

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#2566] opened 2018-10-01 14:16 UTC
#### Expected Behavior
No exception is thrown when deserializing a json representing a `SerializedInsight`.

#### Actual Behavior
> Newtonsoft.Json.JsonSerializationException: 'Error converting value {null} to type 'System.Decimal'. Path 'estimated-value', line 1, position 37098.'

#### Potential Solution
Change `SerializedInsight.EstimatedValue` type to `Nullable<System.Decimal>`.

#### Reproducing the Problem
Change 'estimated-value' value to null in `InsightJsonConverterTests.jsonWithScore`  and run `InsightJsonConverterTests.SerializesInsightWithScore` test.

#### System Information
Locally on Windows and QC cloud.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment] 2019-05-28 21:45
I think there might be an issue with the code that generated the json with the `EstimatedValue` as `null`, can't see how that case is possible in the current `master`, when `EstimatedValue` has the default value it will be ignored https://github.com/QuantConnect/Lean/blob/master/Common/Algorithm/Framework/Alphas/Serialization/SerializedInsight.cs#L134 and as is, it can't be null. So seems like the issue is with the code that generated the invalid json, meaning it should have directly ignored `EstimatedValue` if it had the default value, and not set it as `null`.

**Comment by Martin-Molinero** [comment] 2019-09-10 19:26
Closing this issue since it does not seem valid for current `master`. Let's reopen it if we see it happen again.

**Closed by Martin-Molinero** 2019-09-10 19:26 UTC
