### ISSUE TITLE
Training resources during backtests not refilling over time

### ISSUE THREAD

**Issue by adamvvu** [QuantConnect/Lean#4474] opened 2020-05-29 22:24 UTC
#### Expected Behavior
Training resources for the `Train` method should refill the leaky bucket during backtests based on simulated algorithm time, similar to live limits.

#### Actual Behavior
Training resources seem to be limited to 60 minutes/backtest, and throws the error after exceeded:
```
Runtime Error: Algorithm took longer than 10 minutes on a single time loop. CurrentTimeStepElapsed: 
```

#### Reproducing the Problem
```
# Reproducing Timeout errors from self.Train

from QuantConnect import *
from QuantConnect.Algorithm import *

import time

class TestMLTrain(QCAlgorithm):

    def Initialize(self):

        self.SetStartDate(2019,1,1)
        self.SetEndDate(2019,6,1) # Since we train every week, at least 4 weeks needed to hit time limit
        self.SetCash(1000)

        # Test on this asset
        self.AddEquity('SPY', Resolution.Minute)

        # Model will be trained every Sunday at 6:30
        self.Train(self.DateRules.Every(DayOfWeek.Sunday),
                   self.TimeRules.At(6,30),
                   self.TrainModel
                   )

    def OnData(self, data):
        pass

    def TrainModel(self):
        """
        Simulate a training process.
        """
        
        def MyModel():
            """
            Some computational expensive stuff here.
            """
            time.sleep(900) # Simulate training for 15 minutes
            
        start = time.time()

        self.Log('Training model...')
        
        MyModel()
        
        end = time.time()
        elapsed = end-start
        
        self.Log(f'Training completed in {elapsed:.2f} seconds.')
```

Logs:
```

2019-01-01 00:00:00 : | Launching analysis for 944c266695c7377cc8565683e1256ea6 with LEAN Engine v2.4.0.0.8476
-- | --
2019-01-07 09:31:00 : | Training model...
2019-01-07 09:31:00 : | Training completed in 900.01 seconds.
2019-01-14 09:31:00 : | Training model...
2019-01-14 09:31:00 : | Training completed in 900.01 seconds.
2019-01-22 09:31:00 : | Training model...
2019-01-22 09:31:00 : | Training completed in 900.01 seconds.
2019-01-28 09:31:00 : | Training model...
2019-01-28 09:31:00 : | Training completed in 900.03 seconds.
2019-02-03 06:30:00 : | Runtime Error: Algorithm took longer than 10 minutes on a single time loop. CurrentTimeStepElapsed: 5.0 minutes
2019-02-03 06:30:00 : | Algorithm Id:(944c266695c7377cc8565683e1256ea6) completed in 3901.89 seconds at 0k data points per second. Processing total of 17,324 data points.
```

#### System Information
LEAN master v8476 on QC Cloud

**Comment by adamw96** [comment] 2020-05-29 22:32
Also seems like scheduled training outside of market hours are delayed until market open. In the example, `TrainModel()` is scheduled every Sunday at 6:30 AM but logs indicate training starts Mondays at 9:31 AM.

**Comment by Martin-Molinero** [comment] 2020-05-30 00:50
Hey @adamw96! Actually by design, it's currently refilling based on realtime, not algorithm time (related discussion https://github.com/QuantConnect/Lean/pull/3743#discussion_r336588789), using algorithm time would mean almost unlimited CPU time in practice since time advances so fast

**Comment by adamw96** [comment] 2020-05-30 09:42
Thanks @Martin-Molinero - glad to see there's been a discussion on this, but wouldn't refilling on algorithm time make the backtest behavior more consistent with live behavior?

For example, let's suppose in a backtest an algorithm calls `.Train()` every simulated week, with each call ~15 minutes. Since very few backtests take longer than 24 real hours, we assume no refills for now which implies a fixed 60 minute training capacity per backtest.

If we backtest on 1 month of data, then `.Train()` gets called 4 times. This means that each call has an effective training capacity of 60/4 = 15 minutes in order for the full backtest to run without throwing a timeout error. However for longer backtests:

**Backtest period:** 3 months
**Number of Train() calls: ** 12
**Effective training capacity per call:** 5 minutes
--
**Backtest period:** 1 year
**Number of Train() calls: ** 48
**Effective training capacity per call:** 1.25 minutes
--
**Backtest period:** 5 years
**Number of Train() calls: ** 240
**Effective training capacity per call:** 15 seconds

This implies that for any backtests longer than 1.5 months with regular weekly training, using `.Train()` results in a lower effective training capacity compared to the 10 minute limit of `.OnData()`. As such, currently `.Train()` should only be used for one-time/infrequent calls (i.e. to initialize an algorithm) during a backtest.

As for limiting real CPU time, the current upper limit for a backtest in theory is 10N where N is number of minutes to be backtested (i.e. using the full 10 minutes per minutely call to `.OnData()`). Suppose the leaky bucket algorithm is 60 minute capacity + 10 min/24 hrs. With refilling based on algorithm time, the upper limit is ~(N-60)*0.0069 which is about 1449x lower than the `.OnData()` upper limit for any N. If the goal is to limit real CPU time, wouldn't it make more sense to simply add a fixed time limit (i.e. backtests must be completed in 12 hours or less)?

**Comment by jaredbroad** [comment] 2023-02-17 12:51
Closing as was before QC made the shift to Organizations and AWS-style resource nodes. Now larger nodes have more significant training limits. It's still based on real-time as basing on backtest time would be practically infinite length backtests.

**Closed by jaredbroad** 2023-02-17 12:51 UTC
