### ISSUE TITLE
Coarse Universe Respect Equity Market Hours DB Holidays

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#5004] opened 2020-12-07 00:04 UTC
#### Expected Behavior
LEAN does not run a universe selection on a market holiday.

#### Actual Behavior
Looks like coarse selection run on an observed holiday resulting in 0-data available and deselecting all the assets in the universe.
![image](https://user-images.githubusercontent.com/2243225/101297196-94941e80-37dc-11eb-8b85-b70d0829cab9.png)

#### Potential Solution
The observed holidays are already in the MHDB; we need to make the coarse iterator skip them;
https://github.com/QuantConnect/Lean/commit/3966c0e91f74b3be7bb36ed5dd6bd22aea2636d4

#### Reproducing the Problem
```
class NumberStocksInUniverce(QCAlgorithm):
    
    def Initialize(self):
        self.SetStartDate(2020, 6, 1)  
        self.SetEndDate(2020,11,9)  
        self.SetCash(10000)  
        self.AddUniverse(self.CoarseSelection)
        self.UniverseSettings.Resolution = Resolution.Daily


    def CoarseSelection(self, coarse):
        
        AllSecurities = [ x for x in coarse ]
        self.Plot("Strategy Equity", "AllSecurities", len(AllSecurities))  
        
        if len(AllSecurities) == 0:
            self.Debug(str(self.Time))
        
        Stocks = [x for x in AllSecurities if (x.HasFundamentalData) and (float(x.Price) > 0)]
        self.Plot("Strategy Equity", "Stocks", len(Stocks))
        
        StocksAboveFive = [x for x in Stocks if (x.HasFundamentalData) and (float(x.Price) > 5)]
        self.Plot("Strategy Equity", "StocksAboveFive", len(StocksAboveFive))
        
        TopDollarVolume = sorted(StocksAboveFive, key=lambda x: x.DollarVolume, reverse=True)[:500]
        self.Plot("Strategy Equity", "TopDollarVolume", len(TopDollarVolume))

        return  [x.Symbol for x in TopDollarVolume[:500]]
``` 

#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by gsalaz98** [comment] 2020-12-10 22:29
This was caused as a result of the Market Hours Database not being updated to the most recent version in the cloud NAS, as well as a non-aggregated coarse file that is now being reprocessed. 

Thankfully not a bug, so closing

**Closed by gsalaz98** 2020-12-10 22:29 UTC
Labels: bug
