### ISSUE TITLE
Make Lean a node package

### ISSUE THREAD

**Issue by Worthy7** [QuantConnect/Lean#1374] opened 2017-12-06 01:58 UTC
Can we add a package.json to this repo so that it can be pulled via npm? It would help keep offline development nice and simple (not having to manage cloning and merging)

**Comment by jaredbroad** [comment] 2017-12-11 03:01
Thanks for the issue; if you're not making any changes it should just be "git pull --rebase" right? Why do you need to worry about merging? If you're making changes to LEAN; how would npm allow easier merging?

**Comment by Worthy7** [comment] 2017-12-11 04:02
Yea it is that simple right now, but for example, this means having to set up two separate repositories (one to pull from lean, and one to pull from my own repo). If we aren't touching lean, then I don't really see why we even need to include the sources in our project. But anyway, it was just an idea I thought might be helpful to others too.

**Comment by jaredbroad** [comment] 2017-12-11 04:07
Ok thank you. I think what you described is the best setup for coding an algorithm -- one folder for your algorithm; another for LEAN; and you reference the QCAlgorithm class from your algorithm. Then set LEAN to run the DLL created by your project. I saw a user also trigger LEAN to run after building the algorithm project. 

I'm not too familiar with NPM; I assume your aim is for it to install the compiled code?

**Comment by Worthy7** [comment] 2017-12-11 06:18
To be honest I take it back, I think NPM is supposed to be centered mainly around JS projects, and this is totally not in that category. 
So I guess I'll change this to:
"Please keep the NuGet package up-to-date" 

And then yes, It would be great if our project could be kept clean, just an assembly reference (nuget), some launcher files to load up the Lean launcher and execute.
Can you find the guy who managed to get that simpler project working?

**Comment by jaredbroad** [comment] 2017-12-11 16:15
OK thank you for the clarification, closing as dupe of https://github.com/QuantConnect/Lean/issues/874

You can add a reference to Algorithm folder by right mouse button on references, add reference, select the "Project", navigate to the LEAN folder, and then the Algorithm folder, and QuantConnect.Algorithm project.

**Closed by jaredbroad** 2017-12-11 16:15 UTC
