### ISSUE TITLE
Hilbert Transform Indicator

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#7026] opened 2023-03-01 14:23 UTC
#### Expected Behavior
Support HILBT() Indicator. The Hilbert Transform Indicator was authored by John Ehlers

#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by AlexCatarino** [comment] 2023-03-01 14:30
Duplicate of https://github.com/QuantConnect/Lean/issues/6986.

**Closed by AlexCatarino** 2023-03-01 14:30 UTC
Labels: feature, indicator, good first issue
