### ISSUE TITLE
Forex Internal feeds not subscribed properly when AddCrypto called in Initialize

### ISSUE THREAD

**Issue by StefanoRaggi** [QuantConnect/Lean#1831] opened 2018-04-04 13:44 UTC
#### Expected Behavior
All conversion rates in the `Cashbook` should be nonzero values.

#### Actual Behavior
In the example algorithm, when adding the `AddCrypto` line at the end of `Initialize`, the conversion rates for EUR and JPY are zero.

#### Potential Solution
The issue seems to be with multiple `UserDefinedUniverse`, with subscriptions for internal feeds being added to the wrong universe.

#### Reproducing the Problem
This example algorithm reproduces the issue:
``` C#
public class TestCashBookAlgorithm : QCAlgorithm
{
    public override void Initialize()
    {
        SetStartDate(2018, 3, 1);  //Set Start Date
        SetEndDate(2018, 3, 1);    //Set End Date

        SetCash(10000);
        SetCash("EUR", 10000, 0m);
        SetCash("JPY", 10000, 0m);
        SetCash("BTC", 1m, 0m);

        AddForex("USDJPY");
        AddCrypto("BTCUSD");
    }

    private bool _done;
    public override void OnData(Slice data)
    {
        if (!_done)
        {
            Log($"{Portfolio.CashBook}");
            _done = true;
        }
    }
}
```
Output `without` AddCrypto line:
```
Symbol      Quantity    Conversion = Value in USD
USD: $       10000.00 @       1.00 = $10000.0
JPY: ¥       10000.00 @   0.009361 = $93.61
BTC: ฿           1.00 @   10418.08 = $10418.08
EUR: €       10000.00 @     1.2193 = $12193.30
-------------------------------------------------
CashBook Total Value:                $32705.00
```
Output `with` AddCrypto line:
```
Symbol      Quantity    Conversion = Value in USD
USD: $       10000.00 @       1.00 = $10000.0
JPY: ¥       10000.00 @       0.00 = $0
BTC: ฿           1.00 @   10418.08 = $10418.08
EUR: €       10000.00 @       0.00 = $0
-------------------------------------------------
CashBook Total Value:                $20418.08
```

#### System Information
n/a

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment] 2018-12-24 20:57
This issue won't happen when calling `SetCash()` during algorithm initialize after PR https://github.com/QuantConnect/Lean/pull/2751 because we will be seeding the security initial price + adding a subscription for it.
For the case of adding a new cash instance during execution, which should not be performed by the user but could be done by the `BrokerageTransactionHandler`, in this rare case see https://github.com/QuantConnect/Lean/blob/master/Engine/TransactionHandlers/BrokerageTransactionHandler.cs#L614, we wont seed the security so there could be a delay (due to time zones) until the first data is sent in. See https://github.com/QuantConnect/Lean/blob/master/Algorithm.CSharp/SetCashOnDataRegressionAlgorithm.cs#L57 regression tests that simulates this case.

**Comment by Martin-Molinero** [comment] 2023-02-14 22:52
Closing for now, see previous comment

**Closed by Martin-Molinero** 2023-02-14 22:52 UTC
Labels: bug
