### ISSUE TITLE
Currency internal subscriptions not added with non-USD account currency

### ISSUE THREAD

**Issue by StefanoRaggi** [QuantConnect/Lean#2885] opened 2019-02-05 10:15 UTC
#### Expected Behavior
All required subscriptions should be added for conversions to account currency.

#### Actual Behavior
When using a non-USD account currency and adding a crypto pair which does not include the account currency, the required internal currency pair is not added automatically. 
An exception similar to this is thrown:
```
During the algorithm initialization, the following exception has occurred: 
In order to maintain cash in BTC you are required to add a subscription for Forex pair BTCETH or ETHBTC
```

#### Potential Solution
Add the missing `ETHBTC` pair (and others which might be needed in other cases) to `Currencies.CryptoCurrencyPairs`

#### Reproducing the Problem
This simple algorithm throws an exception:
``` C#
    public class BasicTemplateAlgorithm : QCAlgorithm
    {
        public override void Initialize()
        {
            SetAccountCurrency("ETH");

            SetStartDate(2018, 4, 4);
            SetEndDate(2018, 4, 4);
 
            SetCash(10);

            AddCrypto("BTCUSD");
        }
}
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment] 2019-02-18 12:40
Possible duplicate of https://github.com/QuantConnect/Lean/issues/2060? Which seems like the underlying issue here

**Closed** 2019-02-20 18:13 UTC
Labels: bug
