### ISSUE TITLE
Daily chart data in BacktestResultPacket for series "Equity" contains 6 days per week

### ISSUE THREAD

**Issue by MoreDough** [QuantConnect/Lean#461] opened 2016-07-07 08:38 UTC
If timestamps for "Equity" are corrected so data for the series is no longer shifted compared to "Benchmark" and "Daily Performance" (see Issue #460), then the extra day is a sunday where the data value is identical to the value of the previous day with data in the datafile.

To replicate this error: run local backtest with BasicTemplateAlgorithm and in method LeanWinForms.MessagingOnBacktestResultEvent() create a data dump after 
first line "if (packet.Progress != 1) return;"

The data dump can use the following code to adjust from UTC to America/New_York:
var tz = DateTimeZoneProviders.Tzdb["America/New_York"];
var localTimeKeeper = new LocalTimeKeeper(DateTime.UtcNow, tz);
var timestampAsDt = Time.UnixTimeStampToDateTime(timestamp);
localTimeKeeper.UpdateTime(timestampAsDt);
var timestampAdjustedToNewYorkTime = localTimeKeeper.LocalTime;

(Let me know if you need the dump code)

**Comment by jaredbroad** [comment] 2016-07-07 13:08
Duplicate of #458

**Closed by jaredbroad** 2016-07-07 13:08 UTC
