### ISSUE TITLE
[Bug] Fxcm and Oanda not setting Tags/Comments correctly

### ISSUE THREAD

**Issue by HeroKato-Developer** [QuantConnect/Lean#3735] opened 2019-10-16 16:24 UTC
#### Expected Behavior
Using any Order function placing, limits, stops or market orders, does not actually apply the comment/tag to the order sent.
Both Oanda and Fxcm do not work.

#### Actual Behavior
Order Get sent without any comment/tag

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment] 2023-02-17 16:35
Duplicate of https://github.com/QuantConnect/Lean/issues/5777

**Closed by jaredbroad** 2023-02-17 16:35 UTC
Labels: bug, live-trading
