### ISSUE TITLE
Daily chart data in BacktestResultPacket ends one day after PeriodFinish

### ISSUE THREAD

**Issue by MoreDough** [QuantConnect/Lean#459] opened 2016-07-07 08:29 UTC
Daily chart data for "Benchmark", "Daily Performance" and "Equity" ends one day after PeriodFinish.

To replicate this error: run local backtest with BasicTemplateAlgorithm and in method LeanWinForms.MessagingOnBacktestResultEvent() create a data dump after 
first line "if (packet.Progress != 1) return;"

The data dump can use the following code to adjust from UTC to America/New_York:
var tz = DateTimeZoneProviders.Tzdb["America/New_York"];
var localTimeKeeper = new LocalTimeKeeper(DateTime.UtcNow, tz);
var timestampAsDt = Time.UnixTimeStampToDateTime(timestamp);
localTimeKeeper.UpdateTime(timestampAsDt);
var timestampAdjustedToNewYorkTime = localTimeKeeper.LocalTime;

(Let me know if you need the dump code)

**Comment by jaredbroad** [comment] 2016-07-07 13:08
Please only post one issue per related bug/item. All the posts are likely caused by one thing. Duplicate of #458

**Closed by jaredbroad** 2016-07-07 13:08 UTC
