### ISSUE TITLE
Update Link to Dropbox Files in Algorithms

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4086] opened 2020-02-11 23:58 UTC
#### Expected Behavior
The links to Dropbox files of `DropboxBaseDataUniverseSelectionAlgorithm` and `DropboxUniverseSelectionAlgorithm` are valid and we can run algorithms that rely on them.

#### Actual Behavior
Broken links.

#### Potential Solution
Create new files.

#### Reproducing the Problem
Run `DropboxBaseDataUniverseSelectionAlgorithm` and `DropboxUniverseSelectionAlgorithm`. They throw exceptions when they try to fetch the data.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment] 2020-02-12 00:04
Duplicate of https://github.com/QuantConnect/Lean/issues/3602

**Closed by Martin-Molinero** 2020-02-12 00:04 UTC
