### ISSUE TITLE
Can't Set Default Markets in Custom Python Brokerage Models

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6703] opened 2022-10-20 22:54 UTC
#### Expected Behavior

If we define a custom brokerage model in Python, we can set the `DefaultMarkets` property

#### Actual Behavior

If we define a custom brokerage model in Python, we can't set the `DefaultMarkets` property with a Python dictionary

#### Potential Solution

In Common/Python/BrokerageModelPythonWrapper.cs, replace
```
return (_model.DefaultMarkets as PyObject)
    .GetAndDispose<IReadOnlyDictionary<SecurityType, string>>();
```
with 
```
var defaultMarkets = (_model.DefaultMarkets as PyObject).ConvertToDictionary<SecurityType, string>();
                    _model.DefaultMarkets.Dispose();
                    return defaultMarkets;
```

#### Reproducing the Problem

Try to run a python algorithm with a [custom brokerage model](https://www.quantconnect.com/docs/v2/writing-algorithms/reality-modeling/brokerages/key-concepts#06-Model-Structure).

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by DerekMelchin** [comment] 2022-10-20 22:56
Additionally, if we use a custom brokerage model and try to update an order, we get 
> CanUpdateOrder() missing 1 required positional argument: 'message'

**Comment by Martin-Molinero** [comment] 2022-10-21 15:40
Seems duplicate of https://github.com/QuantConnect/Lean/issues/6370

**Closed** 2023-05-02 18:09 UTC
Labels: bug, impact-low
