### ISSUE TITLE
Extract Yahoo Auxiliary Data Generator

### ISSUE THREAD

**Issue by superichmann** [QuantConnect/Lean#6543] opened 2022-08-12 08:06 UTC
#### Expected Behavior
The factor file should be created with the appropriate data.

#### Actual Behavior
An error is returned and the file is not created.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at QuantConnect.ToolBox.FactorFileGenerator.CalculateNextDividendFactor(BaseData dividend, CorporateFactorRow previousCorporateFactorRow)
   at QuantConnect.ToolBox.FactorFileGenerator.CalculateNextFactorFileRow(List`1 factorFileRows, BaseData nextEvent)
   at QuantConnect.ToolBox.FactorFileGenerator.RecursivlyGenerateFactorFile(Queue`1 orderedDividendSplits, List`1 factorFileRows)
   at QuantConnect.ToolBox.FactorFileGenerator.RecursivlyGenerateFactorFile(Queue`1 orderedDividendSplits, List`1 factorFileRows)
   at QuantConnect.ToolBox.FactorFileGenerator.RecursivlyGenerateFactorFile(Queue`1 orderedDividendSplits, List`1 factorFileRows)
   at QuantConnect.ToolBox.FactorFileGenerator.RecursivlyGenerateFactorFile(Queue`1 orderedDividendSplits, List`1 factorFileRows)
   at QuantConnect.ToolBox.FactorFileGenerator.RecursivlyGenerateFactorFile(Queue`1 orderedDividendSplits, List`1 factorFileRows)
   at QuantConnect.ToolBox.FactorFileGenerator.RecursivlyGenerateFactorFile(Queue`1 orderedDividendSplits, List`1 factorFileRows)
   at QuantConnect.ToolBox.FactorFileGenerator.RecursivlyGenerateFactorFile(Queue`1 orderedDividendSplits, List`1 factorFileRows)
   at QuantConnect.ToolBox.FactorFileGenerator.CreateFactorFile(List`1 dividendSplitList)
```

#### Reproducing the Problem
Using latest QuantConnect.ToolBox - 2.5.14395
call to similar function as `FactorFile_CanBeCreatedFromYahooData_Successfully()` with the following ticker:
`COST`

#### System Information
Windows 10
.NET 6.0

**Comment by Martin-Molinero** [comment] 2023-02-16 14:01
TODO: Move Yahoo auxiliary data generator into it's own data source repo

**Comment by jaredbroad** [comment] 2023-02-17 11:24
Duplicate of https://github.com/QuantConnect/Lean/issues/4686

**Closed by jaredbroad** 2023-02-17 11:24 UTC
Labels: bug, refactor, impact-low
