### ISSUE TITLE
Add .Net Core Support

### ISSUE THREAD

**Issue by gaoxiaojun** [QuantConnect/Lean#452] opened 2016-07-04 03:58 UTC
Microsoft has been released .Net Core 1.0.0 and SDK Preview2,

**Comment by jaredbroad** [comment] 2016-07-04 04:18
Thanks @gaoxiaojun! Do you mind giving an example use case to use it in LEAN?

**Comment by bnmanager** [comment] 2016-07-15 01:28
@jaredbroad @gaoxiaojun 

**Universal Windows Apps (UWP)**, (of which I am currently developing an app for), use `.NET Core` as their foundation. Therefore, many useful libraries found in console or WPF programs are simply incompatible with .NET Core. Currently, QuantConnect is one of those.

Also,`.NET Core` is open source and can run on `Windows/Linux/Apple`.

**Comment by jaredbroad** [comment] 2016-07-26 17:03
Thank you @gaoxiaojun @bnmanager. I'll leave this open but from my reading it seems like a mammoth & risky task to convert the platform across. We can start a branch if there is someone to lead the effort.

For now LEAN is cross platform Windows/Linux/Apple via Mono. The only limitation to date is the winforms UX project which is windows only.

**Comment by omencat** [comment] 2017-05-21 04:42
Instead of targeting .net core, the easiest way today to go about this would be to target the [.net standard 2.0 surface](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/). Using the [.net portability analyzer](https://github.com/Microsoft/dotnet-apiport/blob/master/docs/VSExtension/README.md) extension, it looks like QuantConnect.Algorithm.CSharp is 98.47% complete. QuantConnect.Indicators is already 100% complete.

**Comment by lnaie** [comment] 2017-06-19 09:49
yes, just wait for dns 2 release and you should be 99% good to go.

**Comment by wklm** [comment] 2018-01-27 12:17
Any news on that?

**Comment by jaredbroad** [comment] 2018-01-27 12:59
If you click subscribed you'll be notified when there are updates to the
ticket

**Comment by wklm** [comment] 2018-01-27 21:56
I was asking, because if there's no one currently working on it I could give it a try

**Comment by snielsson** [comment] 2018-11-12 04:47
Hi, what is the current status of this ?

**Comment by mamatopian** [comment] 2019-01-22 11:36
Hey guys, any news?

**Comment by omidkrad** [comment] 2020-03-06 03:10
Hi, is migrating to .NET Core in the plans at all?

**Comment by omidkrad** [comment] 2020-03-15 05:00
Or maybe a more appropriate compilation target is [.NET Standard 2.0+](https://dotnet.microsoft.com/platform/dotnet-standard).

**Comment by Leonardo-Ferreira** [comment] 2020-03-19 21:29
I think this can be re-prioritized. @jaredbroad mentioned in several places that Mono 5.12+ has displayed abnormal memory leaks, so why don't we discard mono altogether and go for .Net Core?
This could happen in phases, porting first the C#/F# algorithms support and latter the python support.
Microsoft has already announced that .Net 5 will be based on .Net Core and not the old framework.
I think I can greatly support this effort, I've been through this scenario a few times and was very successful.

**Comment by cmoski** [comment] 2020-03-19 21:34
Totally on board for this transition, all of our modern development efforts are in dotnet core. Currently have a port of LEAN to DOTNET 4.7.2, but that is simply to allow compatibility with the Dotnet Standard 2.0+ surface without totally breaking Python.  Happy to contribute dev time to this initiative.

**Comment by Leonardo-Ferreira** [comment] 2020-03-19 21:49
Porting to core can't be done by simply changing the target of compilation. There are several restrictions and caveats there, specially regarding `Threads` (Thread.Kill doesn't exist for instance), which is something that we see here quite often (not thread.kill but the direct reference to threads)
If I were in charge here, the first step would be creating a new repo, forked from this one, something like QuantConnect/Lean2 or QuantConnect/LeanOnCore. This way the development can happen without disturbance to the main project, but we could feed on any bug correction and etc...
Second, I would create duplicate the project tree, in a way that code could be moved from the regular framework to Core on a easy manner (drag-n-drop). This would leave the project uncompilable for quite some time, but it's a lesson learned... once the code is moved, then we would work on the quirks to get it compiling. Once this is over, delete the original tree
Third phase would be the unit tests... all of them...
I must already advice that this is not an easy undertake and there will be a lot of merge conflicts and lots of headache, but something definitively worth doing.

**Comment by Leonardo-Ferreira** [comment] 2020-03-19 22:11
It's also important to note that we should try to reach as many people as we can, thus targeting .Net Standards such as 1.6 as much as possible.

**Comment by Leonardo-Ferreira** [comment] 2020-03-19 22:54
You can follow my work here: https://github.com/Leonardo-Ferreira/Lean/tree/feature-452-dotNetCore3
ps: I created a channel on net core implementation discussion

**Comment by snielsson** [comment] 2020-03-26 07:44
Great effort thanks. I hope you get some support. I might be able to help later on.

**Comment by yuandong618** [comment] 2020-03-30 06:10
> You can follow my work here: https://github.com/Leonardo-Ferreira/Lean/tree/feature-452-dotNetCore3
> ps: I created a channel for net core implementation discussion on our Slack
> 
> Update 1 (2020-03-20): Happy to report that a compiling and running project is up. There might be bugs and everything but it's up. It's nice to have something I can hit F5 and have running on .net core

how to join the slack channel?

**Comment by Leonardo-Ferreira** [comment] 2020-03-30 18:29
@yuandong618 Check this out: https://www.quantconnect.com/slack

**Comment by Leonardo-Ferreira** [comment] 2020-04-01 22:20
Happy to report that the tests are running!
All python tests are broken because it's not the scope yet to run python lags (but I hope to get this up again soon) and Interactive brokers is also out, but things are moving along!

**Comment by happysammy** [comment] 2020-07-22 09:47
> Happy to report that the tests are running!
> All python tests are broken because it's not the scope yet to run python lags (but I hope to get this up again soon) and Interactive brokers is also out, but things are moving along!

Hey guys, what's the status of  tests?

**Comment by Leonardo-Ferreira** [comment] 2020-07-24 14:47
couldn't work on this any further @happysammy. I noticed they upgraded the framework a bit to comply to .net standard 2.0 I think though

**Comment by eramosr16** [comment] 2020-09-15 16:25
Four years and counting...

**Comment by kgoderis** [comment] 2020-11-15 16:36
@Leonardo-Ferreira @jaredbroad As I discover more and more on QuantConnect, I just stumbled on https://docs.microsoft.com/en-us/dotnet/core/dotnet-five ... Time to take a quantum leap ? ;-)

**Comment by Leonardo-Ferreira** [comment] 2020-11-16 13:39
I backed out a bit from this project... I did went quite far transitioning it to .net core 3.1 but didn't manage to finish it cause they just wouldn't accept the PR... me and @jaredbroad had a long talk @ slack, where I explained what I believed we should do, and how I was proposing to do it. Long story short, I was proposing a incremental approach, where not all features/brokers would be available at day 1, but would be added over time, and this was deemed unacceptable given the relatively small gains...

As I mentioned before, migrating to .Net Core or to .Net 5 is the basically the same effort...

**Comment by kgoderis** [comment] 2020-11-16 14:12
@Leonardo-Ferreira Indeed, in fact, a lot of the components/packages of the solution are quite old, and need to be upgraded. It is the only part that worries me, because advances in ML are quick, and quantconnect risks to become less relevant.

**Comment by kgoderis** [comment] 2020-11-16 14:12
@jaredbroad That being said, is there something like a roadmap for quantconnect/lean ?

**Comment by onionhammer** [comment] 2020-11-16 14:29
@Leonardo-Ferreira doing an incremental approach is actually the recommended approach for large solutions

**Comment by cmoski** [comment] 2020-11-16 16:20
I would have to agree -- as NET5 is here (attempting) unify the frameworks LEAN does run the possibility of becoming less relevent from an ML perspective, espically given the requirements of ML.NET to run only on the latest frameworks.

This should really be on roadmap.

**Comment by Leonardo-Ferreira** [comment] 2020-11-16 21:43
Not to mention the performance improvements. Not only several mundane tasks are faster, they also tend to consume less memory... some are benchmarked here: https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-5/

**Comment by xposure** [comment] 2021-02-15 22:04
I just picked up algo trading recently and was looking at this platform, .net 5 would be a requirement for me so I took the steps...

 - All csprojs are multi-targeted now, you can use `dotnet build -f net462` or `dotnet build -f net50` to build each one.
 - I added `#ifdef net462` as conditional csproj references that aren't needed in .net 5
 - I wrapped code that was using Fxcm and IB with `ifdef`
 - I updated all packages in every project to their latest versions
 - I had to fork R.NET + WebSocket-Sharp to update them to .NET 5 and include them as submodules
 - I had to remove FXCM and IB from .NET 5.0 build options due to lack of support
 - I had to exlude Dukas*  due to lack of SevenZip support
 
I have just started using this library and know very little about it, so I'm hoping another contributor could work with me and run the actual tests to insure that everything is working. I believe there is quite a lot fo requirements for the tests to execute like python, api keys/secrets etc. I can be reached at `xposure#8248` on discord.

The fork can be found at https://github.com/xposure/Lean and here is a result of running QuantConnect.Lean.Launcher with .NET 5 build using `dotnet build -f net50` from the launcher directory and then navigating to `bin\debug` and running `dotnet QuantConnect.Lean.Launcher.dll`.

```
λ dotnet QuantConnect.Lean.Launcher.dll
20210215 22:00:26.580 TRACE:: Config.GetValue(): debug-mode - Using default value: False
20210215 22:00:26.581 TRACE:: Config.Get(): Configuration key not found. Key: results-destination-folder - Using default value:
20210215 22:00:26.582 TRACE:: Config.Get(): Configuration key not found. Key: plugin-directory - Using default value:
20210215 22:00:26.584 TRACE:: Config.Get(): Configuration key not found. Key: composer-dll-directory - Using default value: C:\Users\cphillipd83\Documents\Git\Lean\Launcher\bin\Debug\
20210215 22:00:26.608 TRACE:: Python for .NET Assembly: Python.Runtime, Version=1.0.5.30, Culture=neutral, PublicKeyToken=null
20210215 22:00:26.614 TRACE:: Config.Get(): Configuration key not found. Key: data-directory - Using default value: ../../../Data/
20210215 22:00:26.615 TRACE:: Config.Get(): Configuration key not found. Key: version-id - Using default value:
20210215 22:00:26.616 TRACE:: Config.Get(): Configuration key not found. Key: cache-location - Using default value: ../../../Data/
20210215 22:00:26.616 TRACE:: Engine.Main(): LEAN ALGORITHMIC TRADING ENGINE v2.4.0.0 Mode: DEBUG (64bit)
20210215 22:00:26.621 TRACE:: Engine.Main(): Started 5:00 PM
20210215 22:00:26.622 TRACE:: Python for .NET Assembly: nPython, Version=1.0.5.30, Culture=neutral, PublicKeyToken=null
20210215 22:00:26.623 TRACE:: Config.Get(): Configuration key not found. Key: lean-manager-type - Using default value: LocalLeanManager
20210215 22:00:26.632 TRACE:: JobQueue.NextJob(): Selected QuantConnect.Algorithm.CSharp.dll
20210215 22:00:26.681 TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-capacity - Using default value: 120
20210215 22:00:26.681 TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-time-interval-minutes - Using default value: 1440
20210215 22:00:26.682 TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-refill-amount - Using default value: 18
20210215 22:00:26.682 TRACE:: Config.Get(): Configuration key not found. Key: algorithm-id - Using default value: BasicTemplateFrameworkAlgorithm
20210215 22:00:26.683 TRACE:: Config.GetValue(): job-project-id - Using default value: 0
20210215 22:00:26.683 TRACE:: Config.Get(): Configuration key not found. Key: data-permission-manager - Using default value: DataPermissionManager
20210215 22:00:26.685 TRACE:: Config.Get(): Configuration key not found. Key: results-destination-folder - Using default value: C:\Users\cphillipd83\Documents\Git\Lean\Launcher\bin\Debug
20210215 22:00:26.690 TRACE:: Config.Get(): Configuration key not found. Key: object-store-root - Using default value: ./storage
20210215 22:00:26.691 TRACE:: Config.GetValue(): ignore-version-checks - Using default value: False
20210215 22:00:26.691 TRACE:: AlgorithmManager.CreateTokenBucket(): Initializing LeakyBucket: Capacity: 120 RefillAmount: 18 TimeInterval: 1440
20210215 22:00:26.692 TRACE:: Config.GetValue(): algorithm-manager-time-loop-maximum - Using default value: 20
20210215 22:00:26.696 TRACE:: TextSubscriptionDataSourceReader.SetCacheSize(): Setting cache size to 71582788 items
20210215 22:00:26.844 TRACE:: Loader.TryCreateILAlgorithm(): Loading only the algorithm assembly
20210215 22:00:26.870 TRACE:: Loader.TryCreateILAlgorithm(): Loaded BasicTemplateFrameworkAlgorithm
20210215 22:00:26.876 TRACE:: Config.Get(): Configuration key not found. Key: results-destination-folder - Using default value: C:\Users\cphillipd83\Documents\Git\Lean\Launcher\bin\Debug
20210215 22:00:26.877 TRACE:: LocalObjectStore.Initialize(): Storage Root: C:\Users\cphillipd83\Documents\Git\Lean\Launcher\bin\Debug\storage\BasicTemplateFrameworkAlgorithm
20210215 22:00:26.887 TRACE:: Config.Get(): Configuration key not found. Key: security-data-feeds - Using default value:
20210215 22:00:26.948 TRACE:: BaseSetupHandler.SetupCurrencyConversions():
Symbol      Quantity    Conversion = Value in USD
USD: $      100000.00 @       1.00 = $100000.0
-------------------------------------------------
CashBook Total Value:                $100000.0

20210215 22:00:26.950 TRACE:: BacktestingResultHandler(): Sample Period Set: 04.00
20210215 22:00:26.952 TRACE:: Config.GetValue(): forward-console-messages - Using default value: True
20210215 22:00:26.953 TRACE:: JOB HANDLERS:
20210215 22:00:26.953 TRACE::          DataFeed:     QuantConnect.Lean.Engine.DataFeeds.FileSystemDataFeed
20210215 22:00:26.954 TRACE::          Setup:        QuantConnect.Lean.Engine.Setup.ConsoleSetupHandler
20210215 22:00:26.954 TRACE::          RealTime:     QuantConnect.Lean.Engine.RealTime.BacktestingRealTimeHandler
20210215 22:00:26.954 TRACE::          Results:      QuantConnect.Lean.Engine.Results.BacktestingResultHandler
20210215 22:00:26.954 TRACE::          Transactions: QuantConnect.Lean.Engine.TransactionHandlers.BacktestingTransactionHandler
20210215 22:00:26.954 TRACE::          Alpha:        QuantConnect.Lean.Engine.Alphas.DefaultAlphaHandler
20210215 22:00:26.955 TRACE::          ObjectStore:  QuantConnect.Lean.Engine.Storage.LocalObjectStore
20210215 22:00:26.955 TRACE::          History Provider:     QuantConnect.Lean.Engine.HistoricalData.SubscriptionDataReaderHistoryProvider
20210215 22:00:26.975 TRACE:: AlgorithmManager.Run(): Begin DataStream - Start: 10/7/2013 12:00:00 AM Stop: 10/11/2013 11:59:59 PM
20210215 22:00:27.014 TRACE:: Debug: Launching analysis for BasicTemplateFrameworkAlgorithm with LEAN Engine v2.4.0.0
20210215 22:00:27.015 TRACE:: Config.GetValue(): data-feed-workers-count - Using default value: 16
20210215 22:00:27.015 TRACE:: Config.GetValue(): data-feed-max-work-weight - Using default value: 400
20210215 22:00:27.016 TRACE:: Config.Get(): Configuration key not found. Key: data-feed-queue-type - Using default value: QuantConnect.Lean.Engine.DataFeeds.WorkScheduling.WorkQueue, QuantConnect.Lean.Engine
20210215 22:00:27.016 TRACE:: WeightedWorkScheduler(): will use 16 workers and MaxWorkWeight is 400. Queue type: WorkQueue
20210215 22:00:27.025 TRACE:: Config.GetValue(): show-missing-data-logs - Using default value: False
20210215 22:00:27.059 TRACE:: UniverseSelection.AddPendingInternalDataFeeds(): Adding internal benchmark data feed SPY,SPY,Hour,TradeBar,Trade,Adjusted,Internal
20210215 22:00:27.258 TRACE:: Debug: Purchased Stock: SPY
20210215 22:00:27.317 TRACE:: Synchronizer.GetEnumerator(): Exited thread.
20210215 22:00:27.318 TRACE:: AlgorithmManager.Run(): Firing On End Of Algorithm...
20210215 22:00:27.318 TRACE:: Engine.Run(): Exiting Algorithm Manager
20210215 22:00:27.319 TRACE:: Debug: Algorithm Id:(BasicTemplateFrameworkAlgorithm) completed in 0.36 seconds at 11k data points per second. Processing total of 3,943 data points.
20210215 22:00:27.319 TRACE:: FileSystemDataFeed.Exit(): Start. Setting cancellation token...
20210215 22:00:27.320 TRACE:: FileSystemDataFeed.Exit(): Exit Finished.
20210215 22:00:27.320 TRACE:: DefaultAlphaHandler.Exit(): Exiting...
20210215 22:00:27.343 TRACE:: DefaultAlphaHandler.Exit(): Ended
20210215 22:00:27.343 TRACE:: BacktestingResultHandler.Exit(): starting...
20210215 22:00:27.344 TRACE:: BacktestingResultHandler.Exit(): Saving logs...
20210215 22:00:27.345 TRACE:: Debug: Your log was successfully created and can be retrieved from: C:\Users\cphillipd83\Documents\Git\Lean\Launcher\bin\Debug\BasicTemplateFrameworkAlgorithm-log.txt
20210215 22:00:27.345 TRACE:: BacktestingResultHandler.Run(): Ending Thread...
20210215 22:00:27.345 TRACE:: StopSafely(): waiting for 'Result Thread' thread to stop...
20210215 22:00:27.426 TRACE:: Config.GetValue(): regression-update-statistics - Using default value: False
20210215 22:00:27.426 TRACE::
STATISTICS:: Total Trades 3
STATISTICS:: Average Win 0%
STATISTICS:: Average Loss -1.01%
STATISTICS:: Compounding Annual Return 254.782%
STATISTICS:: Drawdown 2.200%
STATISTICS:: Expectancy -1
STATISTICS:: Net Profit 1.632%
STATISTICS:: Sharpe Ratio 8.371
STATISTICS:: Probabilistic Sharpe Ratio 66.555%
STATISTICS:: Loss Rate 100%
STATISTICS:: Win Rate 0%
STATISTICS:: Profit-Loss Ratio 0
STATISTICS:: Alpha -0.088
STATISTICS:: Beta 1.006
STATISTICS:: Annual Standard Deviation 0.221
STATISTICS:: Annual Variance 0.049
STATISTICS:: Information Ratio -32.586
STATISTICS:: Tracking Error 0.002
STATISTICS:: Treynor Ratio 1.839
STATISTICS:: Total Fees $9.77
STATISTICS:: Fitness Score 0.747
STATISTICS:: Kelly Criterion Estimate 38.64
STATISTICS:: Kelly Criterion Probability Value 0.229
STATISTICS:: Sortino Ratio 79228162514264337593543950335
STATISTICS:: Return Over Maximum Drawdown 85.209
STATISTICS:: Portfolio Turnover 0.747
STATISTICS:: Total Insights Generated 100
STATISTICS:: Total Insights Closed 99
STATISTICS:: Total Insights Analysis Completed 99
STATISTICS:: Long Insight Count 100
STATISTICS:: Short Insight Count 0
STATISTICS:: Long/Short Ratio 100%
STATISTICS:: Estimated Monthly Alpha Value $126657.6305
STATISTICS:: Total Accumulated Estimated Alpha Value $20405.9516
STATISTICS:: Mean Population Estimated Insight Value $206.1207
STATISTICS:: Mean Population Direction 54.5455%
STATISTICS:: Mean Population Magnitude 54.5455%
STATISTICS:: Rolling Averaged Population Direction 59.8056%
STATISTICS:: Rolling Averaged Population Magnitude 59.8056%
STATISTICS:: OrderListHash 17e29d58e5dabd93569da752c4552c70
20210215 22:00:27.430 TRACE:: BacktestingResultHandler.SendAnalysisResult(): Processed final packet
20210215 22:00:27.431 TRACE:: Engine.Run(): Disconnecting from brokerage...
20210215 22:00:27.431 TRACE:: Engine.Run(): Disposing of setup handler...
20210215 22:00:27.431 TRACE:: Engine.Main(): Analysis Completed and Results Posted.
Engine.Main(): Analysis Complete.
20210215 22:00:27.432 TRACE:: Config.GetValue(): close-automatically - Using default value: False
Engine.Main(): Press any key to continue.

20210215 22:00:29.761 TRACE:: Engine.Main(): Packet removed from queue: BasicTemplateFrameworkAlgorithm
20210215 22:00:29.762 TRACE:: LeanEngineSystemHandlers.Dispose(): start...
20210215 22:00:29.762 TRACE:: LeanEngineSystemHandlers.Dispose(): Disposed of system handlers.
20210215 22:00:29.763 TRACE:: LeanEngineAlgorithmHandlers.Dispose(): start...
20210215 22:00:29.764 TRACE:: LeanEngineAlgorithmHandlers.Dispose(): Disposed of algorithm handlers.
20210215 22:00:29.764 TRACE:: Program.Main(): Exiting Lean...
```

**Comment by itsbalamurali** [comment] 2021-02-17 10:28
@xposure  why not a P.R?

**Comment by alex04103** [comment] 2021-02-17 11:00
@xposure I very much appreciate your effort, as simply using .NET 5 instead of mono under linux would be very desirable.

I tried building your solution using JetBrains Rider, but somehow the reference aren't working as expected, the message is always similar to `Metadata file '/home/user/vcs/trading/Lean/Logging/bin/Debug/ref/QuantConnect.Logging.dll' could not be found`. After further verification, the same issue also occurs when using the `dotnet build -f net50` command.

When copying the .dll to the mentioned ref directory manually, the build fails with the next project not being able to find another .dll in a ref directory.

As far as I can diagnose it, the `QuantConnect.Logging` project itself builds successfully, so only the referencing has issues.

**Comment by alex04103** [comment] 2021-02-17 11:24
I was able to resolve the `Metadata file [...] could not be found.` issue by adding `<ProduceReferenceAssembly>true</ProduceReferenceAssembly>` to every .csproj file (except for the submodules).

**Comment by xposure** [comment] 2021-02-17 11:24
@itsbalamurali This is quite a large library and I virtually know nothing about it, so I wouldn't feel confident in a PR right now. What I am going to do is remove all the .net 462 code and simplify the projects. The current csproj files do not play nice with the debuggers in .net core 5. For example, I had to remove all the debug settings from the csharp algorithm project to allow break points to hit, in addition there is a lot of bloat in these csproj files left over from the old profect file format that needs to be cleaned up and removed.

Lastly, I know nothing about python and have no desire to learn anything about python, so its never going to be something I test, hence why I reached out here to see if someone would want to work with me to turn this in to something stable.

**Comment by xposure** [comment] 2021-02-17 11:29
@alex04103 I'm looking in to this attribute, I've never used JetBrains Rider though. This may be what I just said, there is a lot of `old` csproj file things still lingering around. These files look like someone just sort of added the .net sdk attribute at the top and deleted all the compile/folder values. 

According to this https://github.com/dotnet/sdk/issues/2521 that param you set is now the default, so not sure why you have to set it atm.

**Comment by xposure** [comment] 2021-02-17 13:35
Created a new branch `net5`

 - I have removed net462 everywhere, no reason in supporting backwards compatiability.
 - I cleaned up all the csproj files, you can also now build the sln file without issues
 - I removed mono tasks and docker, I will be adding skaffolding and proper docker support today.
 - I removed a lot of the build spam that doesn't seem relevant
 - I added a Directory.Build.props to control the overall settings and removed all the duplicated csproj settings
   - I will also be moving all package reference versions to here too so that package reference versioning files can be located in a single place
   - @alex04103 I have added this attribute to the directory.props.build so its applied to all project files now

My next goal is to build a thin docker image using the .net linux docker image as the base and then add skaffolding support so you can debug inside docker with vscode with a single command.

Once docker support is properly added, I will then create a dotnet template that will create a simple lean project that generates skaffolding, dockerfile and a basic algorithm that will aid it getting people started.

**Comment by xposure** [comment] 2021-02-17 15:05
I have updated the docker file to use .net5 and added additional docker ignore directories, this also uses a build stage instead of pulling from the LEAN's docker as a base. Here is the output of the test run https://gist.github.com/xposure/f8f543a37292377b702965772f63f75b

NOTE: There is an issue with the dotnet restore stage so I have removed `--no-restore` off publish for the time being.

```
# Script for building the project file tar
#find . -name "*.csproj" | tar -cf projectfiles.tar.gz -T -

# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /source

COPY *.sln ./
COPY Directory.Build.props .
ADD projectfiles.tar.gz ./
RUN dotnet restore

# copy everything else and build app
COPY . .
RUN dotnet publish Launcher/QuantConnect.Lean.Launcher.csproj -c release -o /app 

# final stage/image
FROM mcr.microsoft.com/dotnet/runtime:5.0
WORKDIR /app
COPY --from=build /app ./
#ENTRYPOINT ["dotnet", "QuantConnect.Lean.Launcher.dll"]
```

**Comment by eramosr16** [comment] 2021-02-17 15:29
@xposure I just wanna say thank you for you work here. Keep it on, this is a great library.

**Comment by xposure** [comment] 2021-02-17 17:06
Dockerimage is stored at Dockerhub for anyone that wants to play with it.

https://hub.docker.com/r/cphillips83/lean

You should be able to run ` docker run -it --rm cphillips83/lean:1.0.0` and see the correct output. I will work on the dotnet template next.

**Comment by xposure** [comment] 2021-02-17 22:41
This will probably be the last post for awhile. If anyone wants to see this merged it, they will need to help me with the python aspect and the tests to make sure everything is working. There was an extensive refactoring of the project files and I think there needs to be more on the python front. As of now you can install the dotnet template and create a new project with docker integration and testing, I will add debugging later.

I have updated my readme https://github.com/xposure/Lean/blob/master/readme.md and the working branch is https://github.com/xposure/lean/tree/net50

**Comment by xposure** [comment] 2021-02-17 23:08
@itsbalamurali PR created, lets hope it gets some traction

**Comment by xposure** [comment] 2021-02-18 00:20
Its a no go, I will continue to work on my fork since its already proven. Anyone else is more the welcome to use it and contribute to it.

**Comment by xposure** [comment] 2021-02-20 02:43
@Martin-Molinero I hope you take the time to look at my PR that was rejected as all this work was already done in mine.

**Comment by xposure** [comment] 2021-02-21 06:01
As of today its now easier than ever for someone to start testing an algorithm with .NET5.0 and C#. With one simple `dotnet new lean` you will be able to open the project in vscode and simply hit `F5` (or whatever your run and debug hotkey is).

Here are some of the recent changes.

 - I removed the submodules and instead I have simply published new packages as version 5.0.0 of websocketsharp and rdotnet.
 - I turned the Data folder in to a nuget package so that it can be used in other places with a simple package reference and with the below xml below in your `csproj` it will copy the data folder to your build output.
```
  <ItemGroup>
    <Content Include="$(NuGetPackageRoot)\xposure.data\$(XposureData)\data\**">
      <Link>data\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>  
  </ItemGroup>
```
 - Toolbox is now packed, I think I just missed this one when converting.
 - I removed docker support as the default to lower the bar of entry. I will bring back docker support later as an additional template that will focus on adding support to an existing project.

NOTE: Prior to getting started, you will need to watch for version 1.0.2 of https://www.nuget.org/packages/Xposure.Data/ to be listed, due to the size of this package it could take a couple of hours (2 hours later still waiting). I wouldn't suggest using `1.0.0` as this version really hurt build times due to the restore always copying the data folder.

**Comment by jaredbroad** [comment] 2021-02-21 18:25
### .NET Core Update

Hi All, it has been a year or so working on this so I think it is time for an official update. TLDR: A shotgun approach will not work with a delicate financial engine. Contributors welcome but accept it will be a daily grind, not a home run. 

We have been carefully upgrading and testing each library change and putting it into production brick by brick - _for about 3-4 months_ with 2-3 FTE engineers. _This is the true grind of professionals;_ it is easy to mass delete things not understood, and ignore and not test each component. But as LEAN hosts more and more assets it's critical the mentality is one of **perfection**, **precision**, and complete **awareness** of changes and the impact they may have on the users of the platform.

Even in the last few months since we started this work, it has touched more than 2M algorithms - without a blink from the community. Our core team has been upgrading each library, maintaining backward compatibility, running full regression tests, and deploying it all the way through to production. Each upgrade then gets a few days of live deployment through the QC platform -- exposing the new code to _**tens of thousands**_ of users and live testing. Any issues are quickly rolled back and fixed before moving to the next step. 

LEAN needs professionals to continue trail-blazing an institutional-caliber quantitative engine and we'd welcome contributors. The contributors will be given a single library to upgrade, test, and submit back for merge. LEAN has the trust of 140,000 engineers and investors because we do things the right way, the hard way. Perhaps one thing missing is a way for the community to run the regression algorithm suite so we'll try and make this accessible to help improve the iteration cycle.

We estimate the .NET core project will be another month or so before it's merged. By the time is merged it would have been tested on _millions of algorithms, and live traded across thousands of accounts_. In the meantime thank you for your patience and support as we continue pushing this one over the finish line.

**Comment by Midaroh** [comment] 2021-02-25 05:03
@jaredbroad When you make these framework changes, is there some automated regression step in your build process to ensure that the output of all user algorithms are not changed by refactoring?

**Comment by jaredbroad** [comment] 2021-02-26 06:17
It is not possible to check them all or even a significant sample (would take years of computing to check every algorithm).  

However, it would be ideal to run the LEAN regression algorithms for open-source PR's via a GH actions event; we can't ship all the data required to run them with the open-source project. We can put the data somewhere semi-private to install with a GH action regression test setup (and GH secret) -- or we can generate random data which covers the same test cases and host that to run the tests.

**Comment by biiiipy** [comment] 2021-02-28 17:22
Thank you for the update! I do hope that .net5 support comes soon, but it's okey to take time, as long as the plans are publicly shared so we know what to expect :)

**Closed** 2021-05-06 20:23 UTC
