### ISSUE TITLE
DataFrame Slice Throws Error

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6581] opened 2022-08-25 00:11 UTC
#### Expected Behavior

We can run the following snippet without error
```
qb = QuantBook()
symbols = [qb.AddEquity(ticker).Symbol
    for ticker in [
        "AAL",   # American Airlines Group, Inc.
        "ALGT",  # Allegiant Travel Company
        "DAL",   # Delta Air Lines, Inc.
        "LUV"    # Southwest Airlines Company
    ]]
history = qb.GetFundamental(symbols, "ValuationRatios.PERatio", datetime(2014, 1, 1), datetime(2015, 1, 1))
history[symbols[0]]
```

#### Actual Behavior

We get 

![image](https://user-images.githubusercontent.com/38889814/186545587-632a88af-6318-4d8a-87f2-cc91d3a94433.png)

#### Potential Solution

N/A

#### Reproducing the Problem

Run the above snippet in the cloud research environment

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment] 2022-08-25 15:29
Can't reproduce, closing for now until issue can be reproduced/pinned further

**Closed by Martin-Molinero** 2022-08-25 15:29 UTC
