### ISSUE TITLE
Add c# SharpNEAT library

### ISSUE THREAD

**Issue by tactevo** [QuantConnect/Lean#3579] opened 2019-09-17 06:58 UTC
Library Request for:

SharpNeat - [https://github.com/colgreen/sharpneat](url)

> In a nutshell, SharpNEAT provides an implementation of an Evolutionary Algorithm (EA) with the specific goal of evolving neural networks. The EA uses the evolutionary mechanisms of mutation, recombination and selection to search for neural networks with behaviour that satisfies some formally defined problem. Example problems might be how to control the limbs of a simple biped or quadruped to make it walk, how to control a rocket to maintain vertical flight, or finding a network that implements some desired digital logic (such as a multiplexer).

#### Potential Solution

Add the library.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment] 2019-09-18 17:52
Duplicate of #2843

**Closed by jaredbroad** 2019-09-18 17:52 UTC
