### ISSUE TITLE
Daily data in BacktestResultPacket for series "Equity" is shifted one day forward

### ISSUE THREAD

**Issue by MoreDough** [QuantConnect/Lean#460] opened 2016-07-07 08:33 UTC
Daily data in BacktestResultPacket for series "Equity" is shifted one day forward compared to series "Benchmark" and "Daily Performance" when all timestamps are adjusted -5h from UTC to America/New_York.

Series "Benchmark" and "Daily Performance" seem to fit data in file spy.csv, "Equity" is shifted compared to data file.

The difference between the series is because  "Benchmark" and "Daily Performance" are sampled with _previousTime.Date() and "Equity" with _previousTime (including time 05:00:00). 

This is probably related to Issue #458.

To replicate this error: run local backtest with BasicTemplateAlgorithm and in method LeanWinForms.MessagingOnBacktestResultEvent() create a data dump after 
first line "if (packet.Progress != 1) return;"

The data dump can use the following code to adjust from UTC to America/New_York:
var tz = DateTimeZoneProviders.Tzdb["America/New_York"];
var localTimeKeeper = new LocalTimeKeeper(DateTime.UtcNow, tz);
var timestampAsDt = Time.UnixTimeStampToDateTime(timestamp);
localTimeKeeper.UpdateTime(timestampAsDt);
var timestampAdjustedToNewYorkTime = localTimeKeeper.LocalTime;

(Let me know if you need the dump code)

**Comment by jaredbroad** [comment] 2016-07-07 13:08
Duplicate of #458

**Closed by jaredbroad** 2016-07-07 13:08 UTC
