### ISSUE TITLE
Adds Additional Margin Interest Model

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#8272] opened 2024-08-22 20:17 UTC
#### Expected Behavior
LEAN provides margin interest models for a constant rate: ConstantMarginInterestRateModel and based on risk-free rate RiskFreeRateMarginInterestRateModel (e.g. 1.5% above the risk-free rate).

#### Actual Behavior
Only Binance and Bybit Futures margin interest.

#### Potential Solution
Add new models.

#### Reproducing the Problem
N/A

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment] 2024-08-26 21:08
Closed as duplicate of https://github.com/QuantConnect/Lean/issues/6981

**Closed by jaredbroad** 2024-08-26 21:08 UTC
