### ISSUE TITLE
Quandl Data Not Streaming to Research

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#5405] opened 2021-03-18 23:30 UTC
#### Expected Behavior

We can retrieve Quandl data from the backtesting environment and Research.

#### Actual Behavior

We can only retrieve Quandl data in the backtesting environment. See [this related thread](https://www.quantconnect.com/forum/discussion/10925/quandl-values-in-jupyter/p1).

#### Potential Solution

N/A

#### Reproducing the Problem

[This code](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_4d4858b9010eead248f537bc4c5a1a59.html) shows the Quandl data can be retreived in the backtester, but not in Research.

#### System Information

Windows 10. Run in QC web terminal.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by VanBuren77** [comment] 2021-03-26 14:19
Any update on this?

**Comment by C-SELLERS** [comment] 2021-03-30 23:57
Closing this because it is working in master as of today 3/30/2021

![image](https://user-images.githubusercontent.com/41277998/113071118-f5bf7380-9178-11eb-81d6-1d1218ab92ee.png)

**Comment by DerekMelchin** [comment] 2021-04-28 16:37
Re-opened because the issue is occurring again. Run the backtest/notebook that's attached above. 
[Related thread](https://www.quantconnect.com/forum/discussion/11253/issues-accessing-historical-quandl-data-in-research-notebook/p1)

**Comment by fishstoryyy** [comment] 2021-07-25 01:37
Any update on this? Quandl data is not streaming in research environment.

**Comment by Martin-Molinero** [comment] 2021-07-27 00:34
> Quandl data is not streaming in research environment.

How are you reproducing this issue @fishstoryyy mind sharing a project?
Seems to be working correctly, using the algorithm provided above. 
![image](https://user-images.githubusercontent.com/18473240/127076252-ab88c6b9-206e-4396-afa9-9ffd48d186bc.png)

**Comment by fishstoryyy** [comment] 2021-08-02 06:36
Hi Martin,

It seems that I was able to get this fixed by providing my Quandl api key.

**Comment by Marinovsky** [comment] 2022-01-17 16:23
Hey there!
I've just run both algos mentioned in QC Cloud
- https://www.quantconnect.com/terminal/processCache/?request=embedded_backtest_4d4858b9010eead248f537bc4c5a1a59.html
- https://www.quantconnect.com/forum/discussion/11253/issues-accessing-historical-quandl-data-in-research-notebook/p1

and both returned me data. Maybe after some requests of data from Quandl(now NasdaqDataLink) it would need to set the token provided by them.
![image](https://user-images.githubusercontent.com/47573394/149805625-b1332c2f-f6bc-4658-a409-4e71fcc2bea6.png)
![image](https://user-images.githubusercontent.com/47573394/149805738-29ac4c6c-0990-4e51-9171-df1ecfb65c64.png)

**Closed** 2022-01-17 16:37 UTC
