### ISSUE TITLE
Report generator for Live environment

### ISSUE THREAD

**Issue by Romazes** [QuantConnect/Lean#7698] opened 2024-01-16 23:32 UTC
#### Expected Behavior

The expected behavior is that the `live_result.json` file should be parsed successfully through the **Lean.Report** generator, resulting in the generation of a valid and informative report in the `.html` format.

#### Actual Behavior

Upon executing the `QuantConnect.Report` project with the provided `live_result.json` file (Coinbase brokerage), an error was encountered, and the generated report `.html` file turned out to be **empty**. The error message from the command prompt is visible in the attached image.

#### Command Promt: 
![image](https://github.com/QuantConnect/Lean/assets/45608740/caa4bc1a-3407-4095-a1bf-94e70e037d7b)

#### Result of Report in `.html` file:
![image](https://github.com/QuantConnect/Lean/assets/45608740/ecb329cf-98e4-4a42-b163-7303724d7fc6)

#### Potential Solution

Handle empty `live_result.json` (validate on `values == null` or `values == 0` )

#### Reproducing the Problem

1. Use `"environment" : "live-paper" or "live-<some-brokerage>"`
2. Run any **algorithm** to get `report.json` file.
3. Try to run `QuantConnect.Report` project with `report.json` (don't forget setup the `config.json for Report proj)

---
Use my data:
1. Report file: [L-3776803206.json](https://github.com/QuantConnect/Lean/files/13956574/L-3776803206.json) - Coinbase Brokerage
2. Run with using `QuantConnect.Report` project (setup report file in `config.json` file)

#### System Information

OS: Windows 10 x64
test: run on x64 CPU
IDE: Visual Studio 2022

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment] 2024-01-22 15:19
Closing as duplicate of https://github.com/QuantConnect/Lean/issues/6082

**Closed by Martin-Molinero** 2024-01-22 15:19 UTC
Labels: bug
