### ISSUE TITLE
Volume Profile Indicator Does Not Distribute Volume over the Trader Bar

### ISSUE THREAD

**Issue by anthbauer** [QuantConnect/Lean#7084] opened 2023-03-17 01:22 UTC
#### Expected Behavior
The Volume Profile indicator should distribute the volume across the range of the trade bar (high to low).

#### Actual Behavior
All the volume is assigned to the close price which is used in the volumePerPrice calculations. https://github.com/QuantConnect/Lean/blob/master/Indicators/MarketProfile.cs#L201-L213

#### Potential Solution
The ability to pass in a row size to the Volume Profile indicator. Row size could be calculated more granularly from tick size and price per row as well. See here for the parameters passed into this market profile implementation: https://github.com/bfolkens/py-market-profile/blob/master/src/market_profile/__init__.py#L11-L13 

#### Reproducing the Problem
Using daily bars, calculate the volume profile for Apple over a 20 day period. The volume profile calculations will be different than when calculated on ThinkOrSwim or when using the `py-market-profile` package. 

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment] 2023-07-07 23:37
Hey @anthbauer!

> The Volume Profile indicator should distribute the volume across the range of the trade bar (high to low).

I think this behavior could be achieved using hourly/minute data with a higher period?

> All the volume is assigned to the close price which is used in the volumePerPrice calculations.
Using daily bars, calculate the volume profile for Apple over a 20 day period.

This is because of using daily bars, expected behavior I'd say

> The ability to pass in a row size to the Volume Profile indicator. Row size could be calculated more granularly from tick size and price per row as well.

This can be achieved defining a custom data type with this format and adjusting the indicator, creating a custom indicator based on it, to use this new data type.

**Comment by Martin-Molinero** [comment] 2023-08-11 20:15
Closing issue for now

**Closed by Martin-Molinero** 2023-08-11 20:15 UTC
