### ISSUE TITLE
BACKTESTING OPTION DAILY

### ISSUE THREAD

**Issue by rgil65** [QuantConnect/Lean#1491] opened 2018-01-19 10:43 UTC
Hi I need to do a backtest of options but I only have the daily data of the chainoptions. Is there anyone who is working on it? The only alternative is to develop your own piece of code for daily data usage?

**Comment by jaredbroad** [comment] 2018-01-19 14:14
Welcome! Its not implemented. Closing as duplicate of #941

**Closed by jaredbroad** 2018-01-19 14:14 UTC
