### ISSUE TITLE
Pre-mature split adjustment on daily resolution bar

### ISSUE THREAD

**Issue by LouisSzeto** [QuantConnect/Lean#6835] opened 2023-01-04 13:22 UTC
#### Expected Behavior
Split adjustment on day T 00:00am should happen beginning on the next slice (day T+1 00:00am) for daily-aggregated bar, as the same slice is referring to the trading day T-1.

#### Actual Behavior
It happened on the same slice on day T.

#### Potential Solution
Handle split after setting OHLCV for the aggregated bar on the same slice.

#### Reproducing the Problem
Flawed backtest (daily bar):
https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_45267ea69b350432e5ce08e045a2411b.html
```
2022-08-24 00:00:00 : | StartTime:8/23/2022 12:00:00 AM EndTime:8/24/2022 12:00:00 AM TSLA: O: 874.56 H: 896.51 L: 863.78 C: 889.36 V: 20549062
2022-08-25 00:00:00 : | StartTime:8/24/2022 12:00:00 AM EndTime:8/25/2022 12:00:00 AM TSLA: O: 297.5633 H: 303.6666 L: 296.51 C: 297.0966 V: 18068665
2022-08-25 00:00:00 : | Split Occured ---
2022-08-25 00:00:00 : | 8/25/2022 12:00:00 AM Factor: 0.3333333
2022-08-25 00:00:00 : | -------
2022-08-26 00:00:00 : | StartTime:8/25/2022 12:00:00 AM EndTime:8/26/2022 12:00:00 AM TSLA: O: 302.3 H: 302.96 L: 291.61 C: 296.07 V: 49997610
```
Reference (minute bar):
https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_8b78af509f7f171aa7afe93798feddcf.html
```
2022-08-24 15:59:00 : | StartTime:8/24/2022 3:58:00 PM EndTime:8/24/2022 3:59:00 PM TSLA: O: 890.45 H: 890.45 L: 890.02 C: 890.32 V: 93740
2022-08-24 16:00:00 : | StartTime:8/24/2022 3:59:00 PM EndTime:8/24/2022 4:00:00 PM TSLA: O: 890.28 H: 891.58 L: 890.28 C: 891.29 V: 525049
2022-08-25 00:00:00 : | Split Occured ---
2022-08-25 00:00:00 : | 8/25/2022 12:00:00 AM Factor: 0.3333333
2022-08-25 00:00:00 : | -------
2022-08-25 09:31:00 : | StartTime:8/25/2022 9:30:00 AM EndTime:8/25/2022 9:31:00 AM TSLA: O: 302.3 H: 302.94 L: 301.28 C: 302.36 V: 933325
```

#### System Information
NA

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment] 2023-02-21 19:29
This is happening because when we apply a split we adjust holdings, orders & asset prices, see [AlgorithmManager.HandleSplits](https://github.com/QuantConnect/Lean/blob/master/Engine/AlgorithmManager.cs#L748) & [SecurityPortfolioManager.ApplySplit](https://github.com/QuantConnect/Lean/blob/master/Common/Securities/SecurityPortfolioManager.cs#L739). 
Part of the problem is that the split and the daily bar are arriving at the same time, if the daily bars ended accurately in exchange timezone 4PM this issue would not happen. Closing since we will soon address this https://github.com/QuantConnect/Lean/issues/6964

**Closed by Martin-Molinero** 2023-02-21 19:29 UTC
Labels: bug, impact-high
