### ISSUE TITLE
All VS project references to Python.Runtime.dll break after setup.py script is executed. Rebuild fails

### ISSUE THREAD

**Issue by gvickh** [QuantConnect/Lean#2476] opened 2018-09-05 08:05 UTC
#### Expected Behavior
Follow the [Python Support](https://github.com/QuantConnect/Lean/tree/master/Algorithm.Python#quantconnect-python-algorithm-project), after 
[Setup.py](https://github.com/QuantConnect/Lean/blob/master/setup.py) is executed and config.json is update, expect successful re-build in VS

#### Actual Behavior
setup.py breaks references to Python.Runtime.dll in all VS projects of LEAN. Rebuild fails

![vserrorlistpythonruntimedllbreakssolutionexplorer](https://user-images.githubusercontent.com/924545/45079399-14763e80-b125-11e8-9bb8-46d79b9b5e2c.png)
![vserrorlistpythonruntimedllbreaks](https://user-images.githubusercontent.com/924545/45079428-20fa9700-b125-11e8-9a6d-0ed22047026a.png)

#### Potential Solution
Not a show stopper. Manually update all the Python.Runtime.dll references pointing to the newly installed version Python.Runtime.dll will solve the problem. 

Short term solution: Suggest to post a notice in the Python setup instruction for the need of manual update of references after setup.py. 

Long term : setup.py will update the VS project/solution metadata so that no error on rebuilding the solution

#### Reproducing the Problem
follow LEAN Python support instruction mentioned above, build fail observed after solution re-build inside VS

#### System Information
Win10 64 bit
commit  used [aa110d93d506ce9a6f311aae803e658e88cd14a4](https://github.com/QuantConnect/Lean/commit/aa110d93d506ce9a6f311aae803e658e88cd14a4)

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment] 2018-09-05 08:36
In `setup.py` final step, the new `Python.Runtime.dll` is copied to the reference path (`packages/QuantConnect.pythonnet.(version)/lib`). 
Please start a fresh installation. After `setup.py` is executed, checkout `packages/QuantConnect.pythonnet.(version)/lib` as it should have two files: `Python.Runtime.ori` (original dll) and Python.Runtime.dll (the new one built for Windows).

**Comment by gvickh** [comment] 2018-09-05 18:10
Hello Alex,

Current HEAD of master branch of LEAN has [Nuget ver 1.0.5.8/Python.Runtime.dll 2.4.0.0 ](https://github.com/QuantConnect/Lean/blob/aa110d93d506ce9a6f311aae803e658e88cd14a4/AlgorithmFactory/packages.config#L4) specified in VS project files. So this is the version used for initial build of LEAN after user clone from GitHub.
https://github.com/QuantConnect/Lean/blob/aa110d93d506ce9a6f311aae803e658e88cd14a4/AlgorithmFactory/packages.config#L4


Now, when user proceed to configure Python support, [setup.py](https://github.com/QuantConnect/Lean/blob/master/setup.py) under LEAN folder download and build pythonnet from GitHub which has current version of 1.0.5.12. 
https://github.com/QuantConnect/pythonnet/commit/76695b4b4ca474214fb6a4ab8a0237c7607997d4#diff-2eeaed663bd0d25b7e608891384b7298


After pythonnet build finished, setup.py copies & replaces Python.Runtime.dll(ver 1.0.5.12) inside LEAN package folder overwriting the existing 2.4.0.0 version.  

When re-build the solution, VS look for 2.4.0.0 version which is non-existent (renamed with .ori extension to be exact)

I guess this the the reason why the VS complain & references are broken. 

I did a fresh download and build yesterday and has the same problem. I could give it another shot tomorrow when I go back to work.

**Comment by gvickh** [comment] 2018-09-07 09:15
Hello Alex, 

I tried two times to clone from github and setup Python support, and the result is the same. I have to do a manual fix in VS to update all the references to Python.Runtime.dll

**Comment by AlexCatarino** [comment] 2018-09-10 15:57
Hi @gvickh, before PR #2298, we have decided to match the package version with the library one. Once we merge that PR the reference issue will go away. Normally we merge the changes in Lean references just a couple of days after we change out version of pythonnet, but other priorities delayed PR #2298.

**Comment by gvickh** [comment] 2018-09-11 01:59
That's great, thanks Alex.

**Comment by Martin-Molinero** [comment] 2019-03-04 19:31
Closing because after https://github.com/QuantConnect/Lean/pull/2854 this issue has been fixed (no longer valid/reproducible issue).

**Closed by Martin-Molinero** 2019-03-04 19:31 UTC
