### ISSUE TITLE
`CreateOptimization` throws error

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6921] opened 2023-01-30 23:35 UTC
#### Expected Behavior

We can run `CreateOptimization` without error.

#### Actual Behavior

![image](https://user-images.githubusercontent.com/38889814/215620831-191094bf-030f-4889-961a-df2327a1d5c8.png)

![image](https://user-images.githubusercontent.com/38889814/215620871-8eb88b1f-4b13-49fd-a802-37347a98d91d.png)

#### Potential Solution

N/A

#### Reproducing the Problem

Use the code examples above

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by hussainonebeyond** [comment] 2023-02-03 12:10
Can this issue be assigned to me? I was able to reproduce the issue by running units test?

**Comment by hussainonebeyond** [comment] 2023-02-03 14:50
Hi, I have investigated the issue, it seems like it throws an error when it is not been able to connect to the Quant API for various reasons such as missing project, user-id or authentication token, therefore, it generates an empty base-optimization list. even fixing that issue would not pass the unit test. 
Few Questions 
Currently, the unit test is failing because of I don't have the right userId, and authentication token. Is there are test id that can be used for the test to work?
Q2 how can I test this locally with the correct API credentials?

**Comment by Martin-Molinero** [comment] 2023-02-15 23:02
Closing as we are going to be moving API support to the lean CLI

**Closed by Martin-Molinero** 2023-02-15 23:02 UTC
Labels: bug
