### ISSUE TITLE
MarketOnClose / MarketOnOpen orders should be filled at Closing / Opening auction price

### ISSUE THREAD

**Issue by oldrichsmejkal** [QuantConnect/Lean#4655] opened 2020-08-26 14:10 UTC
#### Expected Behavior
MarketOnClose / MarketOnOpen orders should be filled at Closing / Opening auction price

#### Actual Behavior
Auction orders seems to be filled at Bid/Ask price in first/last tick.
This makes huge difference, because in auction is no spread, but in beginning/end of continuous trading is especially huge spread.

(Also mentioned at quantconnect forum: https://www.quantconnect.com/forum/discussion/8705/market-on-close-fill-price/p1 )

#### Potential Solution
For close orders:
In FillModel (https://github.com/QuantConnect/Lean/blob/5efe7b81b8af820b1b1c1f1fd0d47e3c3b932c2c/Common/Orders/Fills/FillModel.cs , line 440)
Instead of:
fill.FillPrice = GetPricesCheckingPythonWrapper(asset, order.Direction).Close;
use just:
fill.FillPrice = asset.Close; #this should be closing auction price, right?

Similar for opening orders.

**Comment by AlexCatarino** [comment] 2020-08-26 14:28
Duplicate of #4567. 
#4567 deals with this problem, since we are reviewing not only Limit, StopMarket, and StopLimit orders, but also MOO and MOC. I have renamed the issue to make it clearer.

Basically, we need to make sure that we get the `Open` for MOO and the `Close` of MOC for a `TradeBar` since it has the official market opening and closing prices respectively.

**Closed by AlexCatarino** 2020-08-26 14:28 UTC
